### ISSUE TITLE
Texto inicial de cada referência deveria ser escrita em Caixa Alta

### ISSUE THREAD

**Issue by laurocesar** [abntex/biblatex-abnt#1]
O texto inicial de cada referência, comumente o sobrenome de cada autor, deveria estar com caixa alta, mas está escrita em versalete

**Comment by danielbmarques** [comment]
Isso é controlado pelas opções `scbib` (small caps na bibliografia) e `sccite` (small caps nas citações). 😉

**Comment by laurocesar** [comment]
Muito massa!

**Comment by danielbmarques** [comment]
Depois dá uma olhada no [manualzinho que eu fiz](https://github.com/abntex/biblatex-abnt/blob/master/biblatex-abnt.pdf). As mudanças necessárias pra funcionar com os arquivos `.bib` do `abntex2cite` estão na seção 5 (mas isso é o mínimo necessário, em muitos casos o `biblatex` tem jeitos melhores de fazer as mesmas coisas, ainda não documentei tudo).
