### ISSUE TITLE
Ordem da numeração no sistema numérico

### ISSUE THREAD

**Issue by ycherem** [abntex/biblatex-abnt#11]
As referências, no sistema numérico, poderiam ser ordenadas de acordo com a chamada no texto (atualmente, estão ordenadas segundo a ordem alfabética). A opção `sorting=none` não funciona.

**Comment by danielbmarques** [comment]
Que coisa, deveria funcionar… que eu saiba não mexi nisso. Agora estou meio sem tempo, mas vou dar uma olhada assim que possível. Se você puder postar um exemplo mínimo ajudaria.

**Comment by danielbmarques** [comment]
Fiz um teste rápido e me parece que está funcionando:

```tex
\documentclass[a4paper]{article}
\usepackage[brazil]{babel}
\usepackage[
    backend = biber, 
    style = abnt-numeric,
    language = brazil,
    sorting = none,
]{biblatex}

\addbibresource{teste.bib}

\begin{filecontents}{teste.bib}
@book{a, author = {a}}
@book{b, author = {b}}
@book{c, author = {c}}
\end{filecontents}

\begin{document}
    \cite{c} \cite{b} \cite{a}
    \printbibliography    
\end{document}
```

Sem `sorting = none`:

![captura de tela 2016-07-09 as 17 54 23](https://cloud.githubusercontent.com/assets/15813674/16710250/69b6f9dc-45fe-11e6-96fa-4cb3f659a849.png)

Com `sorting = none`:

![captura de tela 2016-07-09 as 17 54 38](https://cloud.githubusercontent.com/assets/15813674/16710251/72723fe6-45fe-11e6-8700-c4c4fc91042f.png)

**Comment by ycherem** [comment]
Daniel, tem razão. A versão nova não funciona com versões anteriores do `biber` ou `biblatex`. Funciona perfeitamente depois da atualização. Obrigado.

**Comment by danielbmarques** [comment]
É, por isso mudei a versão para 2.0; vou continuar seguindo o versionamento semântico. Sem problemas. :)
