### ISSUE TITLE
Package biblatex Error: Style 'abnt-ibid' not found

### ISSUE THREAD

**Issue by paulochf** [abntex/biblatex-abnt#12]
Estou tendo esse erro aí. Fiz o seguinte:

- segui [esta instalação do LaTeX](http://tex.stackexchange.com/questions/1092/how-to-install-vanilla-texlive-on-debian-or-ubuntu/95373#95373);
- usando o `tlmgr` instalei o `biber`;
- clonei este repo e copiei os arquivos da pasta `latex` para `/usr/local/texlive/texmf-local/tex/latex/biblatex-contrib/biblatex-abnt`;
- fiz as mudanças para deixar de usar o `abntex2cite` do trabalho pelo `biblatex-abnt`
    - `\usepackage[style=abnt-ibid,language=brazil]{biblatex}`
    - `\addbibresource{<arquivo>.bib}`
    - `\footciteref` -> `\footcite`
- compilei.

```
/usr/local/texlive/2016/texmf-dist/tex/latex/biblatex/biblatex.sty:13001: Package biblatex Error: Style 'abnt-ibid' not found. [\RequireBibliographyStyle{\blx@bbxfile}]
/usr/local/texlive/2016/texmf-dist/tex/latex/biblatex/biblatex.sty:13002: Package biblatex Error: Style 'abnt-ibid' not found. [\RequireCitationStyle{\blx@cbxfile}]
```

Agradeço pela ajuda!

**Comment by dbmrq** [comment]
Uhm, você copiou todos os arquivos `.bbx`, `.cbx` e `.lbx` direto para o diretório `...biblatex-contrib/biblatex-abnt/`? Tente copiar direto, sem as pastas `bbc/`, `cbx/` etc.

Caso você já tenha feito isso, a primeira coisa que eu tentaria é rodar `sudo texhash` e tentar de novo.

Se não der certo, tenta copiar esses arquivos direto pra pasta do documento que você está compilando. Se funcionar, o problema é de fato a localização dos arquivos.

Tente também usar só o estilo `abnt` pra ver o que acontece. E tente também um estilo padrão, tipo `authoryear`. Assim vamos circunscrevendo melhor o problema.

Se ainda não funcionar, me diga o que acontece.

**Comment by paulochf** [comment]
Estranho...
Uso Zsh, e ontem configurei o PATH, tanto é que consegui usar o `pdflatex`.

```
$ which texhash
/opt/texbin/texhash
$ sudo texhash
sudo: texhash: command not found
```

**Comment by dbmrq** [comment]
Que estranho. Mas que bom que deu certo então. :)

Se você encontrar algum problema no estilo me avise.
