### ISSUE TITLE
Processamento de referências por página

### ISSUE THREAD

**Issue by paulochf** [abntex/biblatex-abnt#13]
Eu não soube como escrever o título da issue. Por favor, se achar necessário, edita ele.

Quando uma referência é citada em 2 páginas consecutivas ocorre o seguinte:

![image](https://cloud.githubusercontent.com/assets/107470/19216647/dae944f0-8d9a-11e6-9bb1-894f9bc1b78d.png)

![image](https://cloud.githubusercontent.com/assets/107470/19216642/c8bacc2c-8d9a-11e6-84fc-91071f352c7e.png)

que provavelmente deve estar seguindo a norma. Porém, a regra da universidade do trabalho que estou editando pede para que se reinicie o processamento das referências a cada página. No caso citado, a 1a imagem deveria se repetir na página seguinte também. Idem/Ibidem funcionariam normalmente.

A pergunta é: existe alguma forma de forçar esse comportamento? Poderia ser indicando a parte do código do seu pacote em que eu poderia alterar na versão do meu local, ou ainda utilizando algo equivalente, por exemplo, `\footnote{\bibentry{ref_a}}` (só quis indicar a idéia).

Obrigado!

Update: descobri o `\footfullcite{}`! Só não vou fechar a issue porque pode ser que eu sofra com algum Idem/Ibidem/Apud hehe.

**Comment by dbmrq** [comment]
Amanhã eu posso te responder melhor com o código completo, mas enquanto
isso, se quiser ir tentando resolver, você pode olhar o arquivo cbx… em
algum lugar tem a definição da macro `\footcite` (algo como "newbibmacro"),
e nessa definição é decidido que formato é usado. Quando é a primeira vez
na página, é usada a macro `footcite:short`, acho… você tem que mudar pra
macro que expande pro formato completo, não lembro o nome. E não precisa
mudar o arquivo, você pode copiar só a definição da macro relevante e colar
no preâmbulo do seu documento.
Em sáb, 8 de out de 2016 às 21:13, Paulo Haddad <notifications@github.com>
escreveu:

**Comment by paulochf** [comment]
Agora o problema é esse aqui:

![image](https://cloud.githubusercontent.com/assets/107470/19217020/75dcfcae-8daa-11e6-81e0-170dcd8ee3bc.png)

Eu esperava que a referência [9] ficasse no formato da [6], com _op. cit._. Tentei achar o algum trecho referente a isso no abnt-ibid.cbx e usar alterado no meu preâmbulo, mas não deu certo e reverti ao original.

Aceito sua ajuda amanhã sim, se você puder. Muito obrigado!

**Comment by dbmrq** [comment]
Foi mais fácil do que eu esperava. É só acrescentar o seguinte ao seu preâmbulo:

```tex
\DeclareCiteCommand{\footcite}[\mkbibfootnote]%
  {\usebibmacro{prenote}}%
  {\iffirstonpage{\citereset}{}%
   \usebibmacro{citeindex}%
   \usebibmacro{footcite}}%
  {\multicitedelim}%
  {\usebibmacro{footcite:postnote}}%
```

Isso supõe, no entanto, que o comando `\footcite` é o único que você vai usar nas suas citações.

O próprio BibLaTeX tem o comando `\citereset`, que reinicia a contagem, como se você nunca tivesse citado nenhum autor antes. O problema é onde usar esse comando. Reiniciar a contagem no começo de cada seção, por exemplo, seria fácil… é só redefinir o comando `\section` pra chamar automaticamente o comando `\citereset`. Fazer isso a cada página, por outro lado, não é tão simples. Nesse caso não existe um comando que a gente possa redefinir e, mais do que isso, o pdfLaTeX (ou seja lá que mecanismo você usar) nem tem como saber onde cada página é quebrada numa primeira passagem -- ele ainda está decidindo como isso vai acontecer.

Então o que eu fiz no exemplo acima foi redefinir o comando `\footcite` pra, se a citação for a primeira da página, chamar o `\citereset`. Só que, se você usar algum outro comando, o `\footcite` pode não ser o primeiro da página, e daí não vai dar certo.

Outra possibilidade seria usar algo como o pacote `fancyhdr` pra chamar o `\citereset` no cabeçalho ou no rodapé de cada página (não sei o que seria melhor), mais ou menos assim:

```tex
\usepackage{fancyhdr}
\pagestyle{fancy}
\lhead{\citereset}
```

E, bom, tem muitas outras possibilidades, talvez haja uma melhor na qual eu não pensei, mas todas vão ser gambiarras como essas. Quando possível, é melhor evitar fazer algo a cada página, preferindo unidades semânticas como "capítulo", "seção" etc.

Boa sorte!

**Comment by paulochf** [comment]
Opa!

Obrigado @dbmrq pelo seu esforço! As idéias foram muito boas! Facilitou muito o trabalho aqui!

Pra terminar, agora é a perfumaria final: onde está a definição do _op. cit._ ? Consegui fazer funcionar o que eu não tinha conseguido [no outro comentário](https://github.com/abntex/biblatex-abnt/issues/13#issuecomment-252459194), mas o itálico nos termos em Latim eu não achei onde alterar.

Muito obrigado pela sua ajuda!

**Comment by dbmrq** [comment]
O que você quer é colocar os termos em itálico, é isso?

É só acrescentar o seguinte ao seu preâmbulo:

```tex
\renewcommand*{\mkidem}[1]{\emph{#1}}
\renewcommand*{\mkibid}[1]{\emph{#1}}
\renewcommand*{\mkopcit}[1]{\emph{#1}}
```

Você pode redefinir esses comandos como quiser, os termos são passados a eles para serem formatados.

**Comment by paulochf** [comment]
Nossa! Mas eu tinha feito isso! Que coisa...

Infinito obrigado!

**Comment by dbmrq** [comment]
Tranquilo.

Tem que ver se você não usou `\providecommand`, como está no arquivo `cbx`. Aí o comando só é definido caso não exista ainda, então adicionar isso ao seu preâmbulo não mudaria nada. ;)
