### ISSUE TITLE
Idem <=> Ibidem

### ISSUE THREAD

**Issue by paulochf** [abntex/biblatex-abnt#14]
Estava vendo aqui nos livros que usamos de referência, e parece que o comportamento do _idem_/_ibidem_ está trocado no pacote.

Que entendi lendo algumas explicações na Internet e pela referência em questão, deveria ser:
- idem: mesmo autor e obra, outra página
- ibidem: mesmo autor obra e página

O pacote faz o contrário:

- documentação do pacote
![documentação do pacote](https://cloud.githubusercontent.com/assets/107470/19224030/0c3ff770-8e53-11e6-8abb-e0e4e8d94bae.png)

- o trabalho compilado
![meu trabalho](https://cloud.githubusercontent.com/assets/107470/19224036/32f9db6a-8e53-11e6-9a3a-85a06df69935.png)

- uma referência usada
![a referência](https://cloud.githubusercontent.com/assets/107470/19224065/07231942-8e54-11e6-9542-0e390d1fb50d.png)

**Comment by dbmrq** [comment]
O estilo segue a norma da ABNT: *idem* para mesmo autor e *ibidem* para mesmo autor e mesma obra.

**Comment by dbmrq** [comment]
Essa issue me chamou atenção para outra coisa. A ABNT não fala nada sobre a possibilidade de omitir a página quando ela é a igual à anterior, mas eu acho que não faz sentido ter diversas notas repetindo a página. Se a página é a mesma, deve aparecer só "ibid.".

Esse parece ser também o consenso entre outros estilos. O manual de Chicago, por exemplo, diz: 

> If all of the reference information is identical, just the word “ibid.” is used. If the page number is different, “ibid.” and the page number are needed.

Então eu decidi fazer essa mudança; o último commit que enviei aqui tem esse comportamento automaticamente.

**Comment by paulochf** [comment]
Muito obrigado, @dbmrq!

Realmente, encontrei outras referências dizendo isso, como [essa aqui](http://www.biblioteca.iq.unesp.br/biblio/dissertacao/rodape.htm), falando justamente o que você falou agora. O meu receio era que tivesse mudado a norma, já que a autora do livro e outros sites que encontrei usaram de forma diferente.

Acabei mantendo o seu jeito mesmo. :)

Muito obrigado, viu? Abs!
