### ISSUE TITLE
URLs ficam com < e > nas referências

### ISSUE THREAD

**Issue by adiel-mittmann** [abntex/biblatex-abnt#16]
O que está acontecendo aqui é que os caracteres `<` e `>` estão sendo incorporados no _endereço_ das entradas na lista de referências, de forma que quando clico no link acontece algum erro porque o endereço é inválido.  Estou usando o campo `url` do BibLaTeX.  Quando uso outro estilo ao carregar o BibLaTeX, o problema não acontece.

Consigo resolver o problema aqui alterando o `abnt.bbx` na seguinte linha:

    \DeclareFieldFormat{url}{\bibstring{url}\addcolon\addspace\url{<#1>}}%

Obrigado.

**Comment by dbmrq** [comment]
@adiel-mittmann Bem observado. Já resolvi o problema, instale manualmente a versão do último commit que deve estar tudo certo. Obrigado!
