### ISSUE TITLE
Autores com título repetido têm um ponto a mais

### ISSUE THREAD

**Issue by ycherem** [abntex/biblatex-abnt#17]
Ver exemplo em abnt-testcase, seção 9.1.

**Comment by dbmrq** [comment]
Ixi, é mesmo. Vou ver se resolvo hoje mesmo. Obrigado!

**Comment by dbmrq** [comment]
Acho que agora está tudo certo.

**Comment by ycherem** [comment]
OK @dbmrq, obrigado!
