### ISSUE TITLE
Negrito no nome do journal ao invés do title

### ISSUE THREAD

**Issue by xR2** [abntex/biblatex-abnt#18]
Ai a gente resolve dar aquela ultima olhada antes de ir na gráfica...

![random](https://cloud.githubusercontent.com/assets/17341234/22342483/537c320e-e3d3-11e6-8591-d5cdf3b04baf.png)

Até o exemplo (6.10 @article) no biblatex-abnt.pdf está assim. 

Pelo que eu entendo do item 6.5 da norma o **título** é que deveria estar em negrito e não o nome do jornal/revista.

Dei uma fuçada no arquivo eu talvez o bug esteja por aqui (Ln 440):

```
\DeclareFieldFormat{journaltitle}{%% >>>
  \iftoggle{ittitles}{%
```

**Comment by dbmrq** [comment]
Eu estou viajando, então não vou conseguir conferir agora, mas tenhi quase certeza de que o correto é assim mesmo.
Dá uma olhada na parte da NBR 6023 referente a artigos e compara os exemplos com o abtn-testcase.pdf.
Se estiver errado mesmo confirma aqui que eu tento te explicar como resolver.

**Comment by ycherem** [comment]
O *título* a que se refere 6.5 é o título *do periódico* ou *livro* do qual o capítulo ou artigo são parte. Continue lendo a norma 6023 e veja os exemplos em **7.5.3.**.
