### ISSUE TITLE
"sineloco" impresso em negrito ao invés de [s. l.]

### ISSUE THREAD

**Issue by douglasrizzo** [abntex/biblatex-abnt#19]
Usando `biblatex-abnt` 3.0, `biblatex` 3.7 e `biber` 2.7. Quando não há localização na entrada, é impresso **sineloco** ao invés de [s. l.]. Segue uma captura de tela.

![screenshot_20170313_214525](https://cloud.githubusercontent.com/assets/2209364/23881070/9e778984-0836-11e7-8491-69bfb59f4e0b.png)

O pacote é chamado da seguinte forma:

    \RequirePackage[backend=biber, safeinputenc=true, isbn=false, doi=false, style=abnt]{biblatex}

Suspeito que seja devido à atualização do biblatex e biber.

Abaixo as entradas utilizadas para gerar a bibliografia em questão.

```
@book{hamlet,
 ISBN = {9780300101751},
 URL = {http://www.jstor.org/stable/j.ctt1njkw8},
 author = {William Shakespeare and Burton Raffel and Harold Bloom},
 publisher = {Yale University Press},
 title = {Hamlet},
 year = {2003}
}

 @Unpublished{lshort,
    author = {Tobias Oetiker and Hubert Partl and Irene Hyna and Elisabeth Schlegl},
    title = {The Not So Short Introduction to {\LaTeXe}},
    month = {apr},
    year = {2014},
    note = {Distribuido digitalmente},
    url={http://tobi.oetiker.ch/lshort/},
 }

@book{mittelbach_latex_2004,
	edition = {2},
	title = {The Latex Companion},
	publisher = {Addison-Wesley},
	author = {Frank Mittelbach and Michel Goossens},
	year = {2004},
}
```

**Comment by dbmrq** [comment]
O texto aparece assim em negrito quando não há tradução do termo pro idioma usado. Se a sua bibliografia estiver em português, chame o BibLaTeX com a opção `language=brazil`, como você pode ver no readme do repositório e no manual. Outra opção é usar os pacotes babel ou polyglossia, assim o BibLaTeX tenta adivinhar o idioma automaticamente. Caso você esteja usando outro idioma, vai ter que traduzir o arquivo `.lbx` para esse idioma, por enquanto eu só fiz para o português.

**Comment by douglasrizzo** [comment]
Vamos ver se te interessa. Eu usava o babel com o idioma `brazil` e não passava o idioma explicitamente para o biblatex. Ele o reconhecia automaticamente. Alguns usuários da [minha classe](https://github.com/douglasrizzo/Classe-Latex-FEI) começaram a ter problemas com esse idioma `brazil`, então eu troquei para `portuges` porque, de acordo com o código do próprio babel, `portuges`, `portuguese`, `brazil` e `brazilian` são todos equivalentes.
Mas aí o biblatex reconhece o `portuges` como pt-PT e não pt-BR. Então, apesar de serem equivalentes para o babel, as diferentes formas de invocar o idioma português não são equivalentes para o biblatex.

Meu problema é com babel e biblatex então, não com seu estilo. Valeu.

**Comment by dbmrq** [comment]
Ah, bem observado! Eu chequei o manual e, de fato, o BibLaTeX só entende o `brazil` como português brasileiro:

![captura de tela 2017-03-14 as 02 08 13](https://cloud.githubusercontent.com/assets/15813674/23886755/2fcb6778-085c-11e7-8f87-dc806fa25503.png)

O último commit deve resolver esse problema, agora o estilo usa o mesmo arquivo lbx para o português brasileiro e europeu. Obrigado! :)
