### ISSUE TITLE
No "et al" in citations

### ISSUE THREAD

**Issue by acmat** [abntex/biblatex-abnt#2]
"Et al" does not appear in text, only in bibliography listings.

```tex
\usepackage[
    backend=biber,
    style=abnt,
    babel=other,
    refsection=section,
    maxbibnames=3,
    maxcitenames=3,
    uniquename=init,	
    giveninits,
]{biblatex}
```

-----------------------------------------------

```tex
@incollection{Tows2009averticalizacao,
   author		= {R. L. Töws and C. M. Mendes and H. M. M. Gimenez and V. P. Druciaki},
   title		= {A verticalização na Produção do Espaço Urbano},
   editor		= {MENDES, C. M.; TÖWS, R. L.},
   editortype	= {Orgs.},
   booktitle	= {A geografia da verticalização em algumas cidades médias no Brasil},
   address		= {Maringá},
   publisher	= {EDUEM},
   year			= {2009},
   pages		= {94-117},
}
```

-----------------------------------------------

nono Töws (2009),
nono (TÖWS, 2009)

-----------------------------------------------
TÖWS, R. L. et al. A verticalização na Produção do Espaço Urbano. In: MENDES C. M.;
TÖWS, R. L. (Orgs.). A geografia da verticalização em algumas cidades médias no
Brasil. Maringá: EDUEM, 2009. pp. 94–117.

**Comment by danielbmarques** [comment]
@acmat 
Por que você fechou a issue? Pelo que eu vi estava errado mesmo.
Agora acho que resolvi o problema:

![et al](https://cloud.githubusercontent.com/assets/15813674/15839291/f0430ed2-2c18-11e6-8b12-abac7e33648b.png)

É só você usar o arquivo `.cbx` atualizado aqui. Se você puder, por favor teste e confirme se está tudo certo.

Obrigado por avisar!

**Comment by acmat** [comment]
Desculpe, Marcos. Pensei que fosse um engano meu. Devo reabrir a questão
(issue)?
Grato pela atenção!
Antonio

Em 6 de junho de 2016 19:01, Daniel Marques <notifications@github.com>
escreveu:

**Comment by danielbmarques** [comment]
Marcos? Meu nome é Daniel! Rs.

Mas agora eu acho que está tudo certo. Quando você puder testar o novo arquivo `.cbx` me avisa, se não tiver mais nenhum problema fechamos aqui.

**Comment by acmat** [comment]
rs,
Liga não, Pedro!
Estou testando agora. Depois informo.


Em 6 de junho de 2016 20:44, Daniel Marques <notifications@github.com>
escreveu:

**Comment by acmat** [comment]
Estes são os resultados que obtive com o .cbx atualizado em 06/06/2016 por Daniel:
These are the results got by using Daniel's .bx file of 06.06.2016:

Ubuntu 14.04 LTS 64-bit, Texlive 2015 Full (https://www.tug.org/texlive/)

\documentclass{memoir}
\usepackage{fontspec}
\usepackage[brazilian]{babel}
\usepackage[backend=biber,style=abnt]{biblatex}
\addbibresource{tumaszjr.bib}
\addbibresource{biblatex-abnt.bib}
\begin{document}
...
\end{document}

![image](https://cloud.githubusercontent.com/assets/19767253/15842072/455ed30c-2c2c-11e6-9bfc-c84cb1f42c17.png)

**Comment by danielbmarques** [comment]
Então está resolvido, né?

**Comment by acmat** [comment]
Apenas o "a" de Moretti (2009a) não aparece aqui.

**Comment by danielbmarques** [comment]
Não entendi. Na imagem que você mandou aparece “2009a”, não é isso?

**Comment by danielbmarques** [comment]
Ou a imagem é para exemplificar e quando você tenta não aparece?

Para que apareça o “a” você precisa citar duas obras com o autor “Moretti” e o mesmo ano, aí são usadas letras pra diferenciá-los.

**Comment by acmat** [comment]
Sim, mostrei o teu resultado, notando que não o havia alcançado.
De fato, eu devia tê-lo citado mais de uma vez para que o índice "a" aparecesse.
Creio que com isso fecha.
Muito grato!

**Comment by danielbmarques** [comment]
Legal!

O estilo ainda é novo, nem tudo foi testado, então me avise se você encontrar mais algum problema. :)
