### ISSUE TITLE
Diferenciar obras com mesmo primeiro autor usando letra na data ao invés de segundo autor

### ISSUE THREAD

**Issue by douglasrizzo** [abntex/biblatex-abnt#20]
**tl;dr:** como diferenciar obras que possuam um mesmo primeiro autor adicionando uma letra na data ao invés de adicionar o nome do segundo autor?

---

Nas obras citadas que contêm um mesmo primeiro autor, as citações e referências estão diferenciando as obras incluindo o nome do segundo autor ao invés de diferenciar pela data ou incluindo uma letra à data. Esse é o comportamento padrão do pacote? Existe uma forma de conseguir o comportamento abaixo descrito abaixo?

Por exemplo,

>  _"No ano seguinte, **Duan, He et al. (2012)** realizaram [...]"_

e

> _"Nesse mesmo ano de 2012, **Duan, Liao et al. (2012)** estudaram [...]"_

deveria ser

> _"No ano seguinte, **Duan et al. (2012a)** realizaram [...]"_

e

> _"Nesse mesmo ano de 2012, **Duan (2012b)** estudaram [...]"_

Exemplos que ocorrem em citações indiretas são os seguintes. No primeiro exemplo abaixo, o nome do segundo autor ainda é incluso, mesmo que a data deste trabalho (2014) seja diferente das datas dos dois trabalhos acima (2012).

> (HÄNGGI et al., 2014; **DUAN; LONG et al., 2014;** KAZEMI; YEKTAYAR; ABAD, 2012; AMIDZIC et al., 2001; NICHELLI et al., 1994)

> (**F. ROCHA; MAGALHAES JUNIOR et al., 2016;** WRIGHT et al., 2013; VOLKE et al., 2002)

E as referências ficam assim:

![image](https://cloud.githubusercontent.com/assets/2209364/24064159/a58dd9d6-0b41-11e7-9baa-fc3c86eda2f3.png)

**Comment by dbmrq** [comment]
Uhm, acho que a ABNT dá margem às duas possibilidades. Hoje está meio corrido, mas quando der vou olhar melhor e mesmo se eu decidir deixar assim eu crio uma opção ou te falo como fazer para mudar.

**Comment by douglasrizzo** [comment]
Beleza. Aviso porque o `abntex2cite` usava as letras ao invés de nomes adicionais de autores ([manual](http://mirror.unl.edu/ctan/macros/latex/contrib/abntex2/doc/abntex2cite-alf.pdf), seção 4.2.9) e, como o `biblatex-abnt` visa substituí-lo, seria interessante ter a opção.

Adicionalmente, a ["norma"](http://www.usjt.br/arq.urb/arquivos/nbr10520-original.pdf) NBR 10520 já é vaga com relação ao uso das letras, quicá mencionar o uso de nomes adicionais de autores.

**Comment by dbmrq** [comment]
Dei uma olhada no manual e para ter o resultado que você quer é só chamar o BibLaTeX com a opção `uniquelist=false`. 🍻

**Comment by douglasrizzo** [comment]
Usei a opção `uniquelist=false` e isso corrigiu as citações, mas as letras não foram adicionadas às datas nas referências bibliográficas. Estou testando as diferentes opções do BibLaTeX aqui, mas está meio difícil entender as opções de desambiguações dele.

Citação:
![screenshot_20170320_183113](https://cloud.githubusercontent.com/assets/2209364/24123151/267f3f0a-0d9d-11e7-8de3-25c619aa7441.png)

Referências:
![screenshot_20170320_183147](https://cloud.githubusercontent.com/assets/2209364/24123153/2852d2c4-0d9d-11e7-9d66-66a7d94a6f25.png)

**Comment by dbmrq** [comment]
As letras nunca são usadas na bibliografia; pode ver que a NBR 6023 nem fala nada sobre isso. A diferenciação é feita só pela ordem alfabética (e.g., 1999a é a primeira entrada na bibliografia e 1999b é a segunda).
