### ISSUE TITLE
Referências justificadas

### ISSUE THREAD

**Issue by kafran** [abntex/biblatex-abnt#22]
Pessoal, eu acho que as referências estão ficando justificadas. Alguém sabe como mudar esse comportamento para "alinhado a esquerda"? (NBR 6023/2002 item 6.3).

**Comment by dbmrq** [comment]
Agora estou viajando, então não vou conseguir olhar, mas a princípio o biblatex-abnt não tem nada a ver com isso, e acho que nem o próprio BibLaTeX: as referências devem ficar como está o restante do seu documento. Se você quer o texto alinhado à esquerda, tenta colocar o `\printbibliography` num ambiente ragged right ou algo assim. Se não der certo reabre a issue e manda um exemplo mínimo que eu dou uma olhada assim que puder.

**Comment by dbmrq** [comment]
Vou reabrir pra me lembrar de transformar esse no comportamento padrão se der, vou ver isso nos próximos dias, mas de qualquer forma imagino que o que eu disse deve funcionar.

**Comment by kafran** [comment]
Eu estou usando o biblatex-abnt com o Abntex2. O documento gerado pelo Abntex2 é justificado, mas as referências segundo a norma devem ser alinhadas à esquerda.

**Comment by ycherem** [comment]
\renewcommand*{\bibfont}{\raggedright}

Youssef Cherem



2017-05-21 15:30 GMT-03:00 Kolmar Kafran <notifications@github.com>:

**Comment by kafran** [comment]
@ycherem Obrigado. Ficou assim:
\clearpage
\renewcommand*{\bibfont}{\raggedright}
\printbibliography

Problema solucionado. Acho que isso deveria ser o comportamento padrão, em respeito à norma. Ou que pudesse ser programável na chamada do pacote. Att.

**Comment by ycherem** [comment]
\clearpage é desnecessário.

Youssef Cherem



2017-05-21 16:28 GMT-03:00 Kolmar Kafran <notifications@github.com>:

**Comment by kafran** [comment]
Nos exemplos que vi tem uma chamada \clearpage antes de imprimir a bibliografia. Vou retirar então. Grato.

**Comment by dbmrq** [comment]
Legal, obrigado, @ycherem.

Quando eu voltar de viagem redefino a `\bibfont` no estilo. Ou se alguém quiser fazer uma Pull Request antes eu aceito.

**Comment by dbmrq** [comment]
Pronto, agora o `biblatex-abnt` usa a opção `block=ragged` do BibLaTeX por padrão. Isso faz com que os diferentes "blocos" da bibliografia (e.g., editora, número de páginas, série) sejam separados com quebras de linha quando necessário, dando uma aparência de texto alinhado à esquerda:

![captura de tela 2017-05-23 as 21 19 17](https://cloud.githubusercontent.com/assets/15813674/26381773/819904a6-3ffd-11e7-93bd-e880e92e3327.png)

Eu vou continuar usando o pacote com a opção `block=space`, que, na minha opinião, dá um resultado melhor, mas vou tentar manter o comportamento padrão o mais perto possível da ABNT (concordo que a norma não faz sentido, mas é o motivo da existência deste estilo, rs.).
