### ISSUE TITLE
et al com mais de 4 autores

### ISSUE THREAD

**Issue by kafran** [abntex/biblatex-abnt#23]
Fala pessoal,

Essa entrada:
```
@Article{Batista2005,
  author       = {Fábio Ferreira Batista and Carlos Olavo Quandt and Fernando Flávio Pacheco and José Cláudio Cyrineu Terra},
  title        = {{G}estão do {C}onhecimento na {A}dministração {P}ública},
  journaltitle = {Texto para discussão},
  date         = {2005-06},
  number       = {1095},
  issn         = {1415-4765},
  address      = {Brasília},
  file         = {:Batista2005 - Gestão do Conhecimento na Administração Pública.pdf:PDF},
  groups       = {GC Adm Pub},
  publisher    = {IPEA},
}
```

Está retornando assim:

BATISTA, F. F.; QUANDT, C. O. et al. Gestão do Conhecimento na Administração Pública. **Texto para discussão**, IPEA, Brasília, n. 1095, jun. 2005. ISSN 1415-4765. Citado na p. 14.

Não deveria ser apenas `BATISTA, F. F. et al.` ??

**Comment by dbmrq** [comment]
Vou dar uma olhada… mas enquanto isso, não tem outra entrada com o mesmo primeiro autor et al.? Pode ser uma opção de desambiguação.

**Comment by dbmrq** [comment]
É isso mesmo, dê uma olhada neste exemplo:

```tex
\documentclass{article}

\usepackage{filecontents}

\begin{filecontents}{\jobname.bib}
    @Article{Batista2005,
      author       = {Fábio Ferreira Batista and Carlos Olavo Quandt and Fernando Flávio Pacheco and José Cláudio Cyrineu Terra},
      title        = {{G}estão do {C}onhecimento na {A}dministração {P}ública},
      journaltitle = {Texto para discussão},
      date         = {2005-06},
      number       = {1095},
      issn         = {1415-4765},
      address      = {Brasília},
      file         = {:Batista2005 - Gestão do Conhecimento na Administração Pública.pdf:PDF},
      groups       = {GC Adm Pub},
      publisher    = {IPEA},
    }   
    @Article{Batista2005b,
      author       = {Fábio Ferreira Batista and Jacinto Pinto and Carlos Olavo Quandt and Fernando Flávio Pacheco},
      title        = {{G}estão do {C}onhecimento na {A}dministração {P}ública},
      journaltitle = {Texto para discussão},
      date         = {2005-06},
      number       = {1095},
      issn         = {1415-4765},
      address      = {Brasília},
      file         = {:Batista2005 - Gestão do Conhecimento na Administração Pública.pdf:PDF},
      groups       = {GC Adm Pub},
      publisher    = {IPEA},
    }    
\end{filecontents}

\usepackage[
    language=brazil, 
    style=abnt,
    %uniquelist=false,
    ]{biblatex}

\addbibresource{\jobname.bib}

\begin{document}
    \nocite{*}
    \printbibliography
\end{document}
```

Se você acrescentar a o opção `uniquelist=false` a desambiguação não acontece.

**Comment by kafran** [comment]
Desculpa não ter respondido mais cedo. Eu não sabia dessa opção de desambiguação, irei desativá-la. De todo o jeito, eu acho que por acaso descobri algum bug. Eu realmente tenho diversas entradas do Batista, entretanto, apenas essa com mais de 3 autores. As outras entradas são do Batista sozinho e apenas uma ele e outro autor e essa do exemplo acima com 4 autores. Ou seja, não era para estar computando esta desambiguação. Você poderia rodar este exemplo e tirar um dos autores de Batista2005b para ver se a desambiguação ainda assim acontece? Fiz esse teste aqui e a desambiguação acontece ainda que haja apenas um "et al."; se esse for realmente o comportamento esperando, desconsiderar. Grato.

**Comment by dbmrq** [comment]
Acho que esse é o comportamento esperado mesmo… talvez as opções de numero máximo e mínimo de nomes tenham alguma influência, teria que olhar o manual do BibLaTeX com mais calma pra ver direitinho. Agora estou sem tempo pra fazer isso, mas ainda que seja mesmo um bug, seria um bug do BibLaTeX, não do biblatex-abnt.
