### ISSUE TITLE
Upcoming changes in biblatex 3.8: origlanguage will become a list

### ISSUE THREAD

**Issue by moewew** [abntex/biblatex-abnt#24]
Apologies for writing in English, unfortunately my Portuguese is abysmal.

In the upcoming and as of now unreleased version 3.8 of `biblatex`, the field `origlanguage` will become a `list`.

Since your style explicitly mentions `origlanguage` it might be affected by the changes
https://github.com/abntex/biblatex-abnt/blob/593d391db3deb2fb4350746669e851a55828566b/latex/bbx/abnt.bbx#L593-L599
https://github.com/abntex/biblatex-abnt/blob/593d391db3deb2fb4350746669e851a55828566b/latex/bbx/abnt.bbx#L1306-L1316

For background info see https://github.com/plk/biblatex/issues/594

You might also want to keep an eye on the other changes in 3.8 https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.org

**Comment by dbmrq** [comment]
No problem, thanks for taking the time to let me know. I'll make the necessary changes. :)

Is there a date for 3.8 to be released? I'll have to send the new version to ctan at about the same time, right?

**Comment by moewew** [comment]
That would be ideal, yes. As of now the release date is not fixed. There are still a few things to consider, a few issues to close, and testing is always appreciated.

If you keep an eye on the official repository you can see when the dev branch is merged into master (https://github.com/plk/biblatex/tree/master) that should be around the time when a new release is submitted (there's also https://github.com/plk/biblatex/releases). Maybe I should ask PLK to announce new releases more prominently.

**Comment by dbmrq** [comment]
Alright, thank you!

**Comment by moewew** [comment]
We are moving closer to a release, see the discussions at the end of https://github.com/plk/biber/issues/164. Nothing is fixed yet, but if everything goes well, it might happen in the next few weeks.

**Comment by dbmrq** [comment]
Ah, ok, I'll keep an eye out. Thanks for letting me know and for all your help. :)

**Comment by moewew** [comment]
A few recent changes to keep your eye on are

-  https://github.com/plk/biblatex/blob/3923e697784681a6443e52d772f8a23f02f3e458/doc/latex/biblatex/CHANGES.org#extrayear-is-now-extradate-and-the-information-used-to-track-this-can-be-customised: `extrayear` is now called `extradate`, backwards compatibility code is in place to let old code continue to work, but you should change to the new name in due time.

- https://github.com/plk/biblatex/blob/3923e697784681a6443e52d772f8a23f02f3e458/doc/latex/biblatex/CHANGES.org#in-order-to-standardise-terminology-some-commands-and-options-have-dropped-the-scheme-naming-convention-and-switched-to-template `\DeclareSortingScheme` is now called `\DeclareSortingTemplate`.

See also https://github.com/plk/biblatex/wiki

**Comment by dbmrq** [comment]
Thank you!

I tried to build the latest version of Biber myself in order to test BibLaTeX 3.8, but gave up after a few failed attempts. It would be nice if the final binaries were available here on Github a few days before ctan to make testing easier. Or maybe even official beta releases for the versions with breaking changes.

**Comment by moewew** [comment]
You can get binaries for Biber and a ready-for-install TDS structure of `biblatex` from sourceforge. 

- https://sourceforge.net/projects/biblatex/files/
- https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/

The builds might be slightly behind the GitHub code base at times.

**Comment by dbmrq** [comment]
Oh, that’s perfect! Thank you. :)

**Comment by dbmrq** [comment]
@moewew I'm running into a problem and I'm not sure if it's a bug with the new version or if I'm doing something wrong… could you help me check it out?

The biblatex-abnt style defines its own `sheet` pagination scheme. It worked with BibLaTeX 3.7, but now I'm testing version 3.8 and it doesn't work anymore. Here's a MWE:

```tex

\documentclass{article}

\usepackage[style=authoryear, language=brazilian]{biblatex}

\begin{filecontents*}{\jobname.bib}
  @book{test,
    author = {John Doe},
    year = {2017},
    pages = {10},
    pagetotal = {20},
    bookpagination = {sheet},
  }
\end{filecontents*}

\NewBibliographyString{
  sheet,%
  sheets,%
  sheettotal,%
  sheettotals,%
}

\DefineBibliographyStrings{brazilian}{%
  sheet        = {f\adddot},%
  sheets       = {f\adddot},%
  sheettotal   = {f\adddot},%
  sheettotals  = {f\adddot},%
}

\addbibresource{\jobname.bib}

\begin{document}
\textcite{test}
\printbibliography
\end{document}
```

I get `Unknown pagination type '' at entry 'test' on input line 34.`, and it prints "f. 10", but "20 pp." (instead of 20 f.). With version 3.7 it worked fine.

Also the manual still says:

> You need to define two localisation strings for each additional pagination scheme: the singular form (whose localisation key corresponds to the value of the pagination field) and the plural form (whose localisation key must be the singular plus the letter ‘s’).

Without mentioning the new `<pagination>total` fields. Should I open an issue on BibLaTeX's repository for this?

**Comment by moewew** [comment]
Yep, thank you for reporting this. The code for `\mkpagetotal` is a bit messed up. I will look at this, you don't have to open an issue at the bugtracker.

**Comment by moewew** [comment]
I have pushed https://github.com/plk/biblatex/commit/d7b354cd1b6fa9b59d395b1db178094dbd75e557 that should resolve the issue. But since 3.8a was only just released it could take some time until this reaches CTAN.

**Comment by dbmrq** [comment]
No problem. I just tried it and now it seems to be working fine. Thank you! :)
