### ISSUE TITLE
Erro em citação com sufixo no nome do autor

### ISSUE THREAD

**Issue by hildogjr** [abntex/biblatex-abnt#25]
Estou utilizando TexLive no Ubuntu, últimas versões oficiais dos pacotes para o Debian.

Ao se criar uma referência em uma arquivo .bib contendo uma autor com sufixo no nome, exemplo SOBRENOME JUNIOR, NOME ou SOBRENOME FILHO, NOME, o autor é citado e listado na lista de referências como JUNIOR, N. S..

Essa não é a forma correta segundo a ABNT, visto que isto não representa o verdadeiro sobrenome do autor.

**Comment by dbmrq** [comment]
O modo correto de citar autores cujo nome tem um sufixo é `{Nome {Sobrenome Júnior}}` ou `{Sobrenome, Júnior, Nome}`. O BibLaTeX ainda tem a opção de especificar cada parte individualmente: `author = {given=Primeiro Nome, prefix=Von, family=Sobrenome, suffix=Júnior}`.

Se você ainda tiver algum problema, envie um [exemplo mínimo compilável](https://tex.meta.stackexchange.com/a/3225/102699), por favor.

**Comment by hildogjr** [comment]
Isso parece apenas uma maneira de se contornar o erro.
Eu sei que a ferramenta trabalha assim, mas seria interessante identificar automaticamente os sufixos padrões `filho, júnior,...` já que, a língua serve justamente para fazer esse serviço de macro.
Passar referência a referência ajustando as configurações me parece perder o automatismo da linguagem LaTEX, é só um ponto de vista.

**Comment by dbmrq** [comment]
Discordo fortemente.

Uma das maiores vantagens (senão a maior vantagem) do LaTeX é a separação entre o conteúdo e a formatação. Assim você pode escrever um artigo para uma revista e, se precisar enviá-lo para outra, pode simplesmente mudar a classe do documento para adequar-se à formatação adequada.

Uma revista pode exigir referências formatadas segundo a ABNT, outra pode exigir o estilo da APA ou de Chicago. Se o seu arquivo `.bib` estiver na sintaxe correta, você só precisa escrever o conteúdo uma vez: quando a revista exigir o formato da ABNT, você usa o estilo `biblatex-abnt`; quando a revista exigir APA, usa o estilo `biblatex-apa`. Se você usar a sintaxe errada, como quer fazer, o estilo `biblatex-apa` não vai reconhecê-la, nem o estilo `biblatex-chicago` e assim por diante.

Se o `biblatex-abnt` reconhecesse o sufixo "Júnior" automaticamente, isso seria uma maneira de contornar o *seu* erro.

**Comment by edusantana** [comment]
@dbmrq no futuro pretendo implementar um serviço web que receba um arquivo `bib` e realize os ajustes dos erros mais comuns e retorne um `bib` com os ajustes.

**Comment by hildogjr** [comment]
Compreendi. Realmente é questão de formatação para o interpretador.

**Comment by dbmrq** [comment]
@edusantana Seria uma boa mesmo, e não deve ser muito difícil. Se eu tiver um tempo posso ajudar. :)

**Comment by mvlp** [comment]
Interessante essa opção de separar o nome.
Fiz o seguinte:
author = {given=Alexandre, family=Assaf, suffix=Neto}
citação indireta no texto => Assaf (ANO)
Lista de referências => ASSAF NETO, A. 

É esse o comportamento correto segundo a norma?

Outro teste que fiz foi com prefixo
author = {given=John, prefix=von, family=Neumann, useprefix=true}
citação indireta no texto => von Neumann (ANO)
Lista de referências => VON NEUMANN, J.  (em versalete o {V} de von apareceu maior que o restante)

att,

**Comment by dbmrq** [comment]
@mvlp Obrigado, vou reabrir esta issue pra lembrar de dar uma olhada.
