### ISSUE TITLE
Citações com múltiplos artigos com múltiplos autores

### ISSUE THREAD

**Issue by mvlp** [abntex/biblatex-abnt#26]
Prezados, 

Indentifiquei algumas formatações estranhas e creio que eles estão fora do padrão abnt. Estou escrevendo minha tese e tenho um documentclass{abntex2}, mas utilizo biblatex-abnt+biber para citações.
Resultado do comando \cite{} ou \cites{} com múltiplos autores:
a) (REGNAULT, 1863; BACHELIER, 1900; FAMA, 1965; SAMUELSON, 1965) => OK
b) (KIM; KIM; AHN et al., 2013; KIM; KIM; FABOZZI, 2014b) => erro, deveria ser: (KIM, KIM, AHN et al., 2013; KIM, KIM, FABOZZI, 2014b), certo?

Outra observação: quando utilizo a opção "sccite" e "scbib" as iniciais dos nomes dos autores não ficam formatadas em versalete.

Além disso, gostaria de parabenizá-los pois ficou muito bom o trabalho de vocês.

att,
Marcos

**Comment by dbmrq** [comment]
Uhm, o problema é os pontos e vírgulas em vez de vírgulas, é isso?

Vou dar uma olhada assim que puder. Nos próximos dias já devo conseguir resolver.

Se você puder enviar um [exemplo mínimo compilável](https://tex.meta.stackexchange.com/a/3225/102699) daria uma boa adiantada.

**Comment by dbmrq** [comment]
Dei uma olhada na NBR 10520 e a ABNT não é muito clara sobre isso (como sempre), mas os exemplos parecem indicar que o nome de cada autor deve ser separado por um ponto e vírgula, como o `biblatex-abnt` faz:

![afe1f12f-0689-45cd-a558-3dcd67f7b131](https://user-images.githubusercontent.com/15813674/31525709-b11efbc6-af98-11e7-92e0-d6425bb4ea96.jpeg)

![2bbf078e-77d7-46cf-bba0-118f28027ebf](https://user-images.githubusercontent.com/15813674/31525708-b0f186b4-af98-11e7-80ca-2867a0d6eab7.jpeg)

O problema do versalete vou resolver em breve. :)

**Comment by dbmrq** [comment]
Pronto, acho que agora está tudo certo. Se você puder testar e confirmar eu agradeço. :)

**Comment by mvlp** [comment]
Olá Daniel,Obrigado pela resposta rápida.Você tinha razão, a parte de citação indireta entre parênteses separa os autores por ";", depois o ano por "," e os trabalhos por ";". Eu fui pela lógica que o ";" deveria servir somente para separar os artigos pois facilitaria a leitura.
A alteração que você fez no versalete na abreviação do nome resolveu o que te pedi, porém trouxe outro problema. A citação indireta sem parênteses ficou em letras maiúsculas e versalete.antes: Segundo Kahneman e Tversky (1979) (fonte do corpo do texto => no nome dos autores quanto no ano)
agora: Segundo KAHNEMAN e TVERSKY (1979) (Nome dos autores em versalete e ano na fonte do corpo do texto)

Creio que o formato anterior era o correto.att,Marcos



      De: Daniel Marques <notifications@github.com>
 Para: abntex/biblatex-abnt <biblatex-abnt@noreply.github.com> 
Cc: mvlp <marcos_vlp@yahoo.com.br>; Author <author@noreply.github.com>
 Enviadas: Sexta-feira, 13 de Outubro de 2017 3:03
 Assunto: Re: [abntex/biblatex-abnt] Citações com múltiplos artigos com múltiplos autores (#26)
  
Pronto, acho que agora está tudo certo. Se você puder testar e confirmar eu agradeço. :)—

**Comment by dbmrq** [comment]
Argh, eu arrumo uma coisa e estraga outra, sempre assim. A última versão deve resolver o problema. Se você puder dar mais uma testada geral eu agradeço, não sei se não quebrei mais nada, rs.

**Comment by mvlp** [comment]
Olá Daniel,Eu fiz um exemplo mínimo aqui e estou te mandando em anexo.
Os erros que identifiquei agora são os seguintes:a) No texto:
=> citação indireta entre parenteses (\cite{})
somente sobrenome em versalete, iniciais do nome, ano e "et al." em fonte do corpo do texto

=> citação indireta sem parenteses (\textcite{}) => ok

b) Nas Referências:Nome e sobrenomes em versalete, porém o "et al." aparece em fonte normal.
Além disso, gostaria de te fazer um pedido, se for possível. Não é algo que existe na norma abnt mas eu verifiquei que isso ocorre quando uso biblatex e estilo APA ou outros estilos internacionais. Ao fazer download de arquivos bibtex de sites de "journals" as vezes os títulos aparecem em "uppercase". Entretanto ao usar a referência ele aparece apenas com a primeira letra do título em maiúsculo e o resto é convertido pra "lowercase", exceto se o usuário colocar algum texto entre chaves dentro do bibtex, por exemplo : title= {An {API} for Image Processing.}.
att,Marcos

      De: Daniel Marques <notifications@github.com>
 Para: abntex/biblatex-abnt <biblatex-abnt@noreply.github.com> 
Cc: mvlp <marcos_vlp@yahoo.com.br>; Author <author@noreply.github.com>
 Enviadas: Sexta-feira, 13 de Outubro de 2017 16:25
 Assunto: Re: [abntex/biblatex-abnt] Citações com múltiplos artigos com múltiplos autores (#26)
   
Argh, eu arrumo uma coisa e estraga outra, sempre assim. A última versão deve resolver o problema. Se você puder dar mais uma testada geral eu agradeço, não sei se não quebrei mais nada, rs.—

**Comment by dbmrq** [comment]
@mvlp Não recebi o exemplo mínimo… mas pelo que você descreveu o comportamento parece correto. Só o nome dos autores é capitalizado, o "et al." é impresso normalmente:

<img width="855" alt="captura de tela 2017-10-14 as 12 34 22" src="https://user-images.githubusercontent.com/15813674/31576955-4a6bffc4-b0dc-11e7-9eec-3afee070a0b7.png">

E as iniciais nem aparecem nas citações, só na bibliografia… a não ser que seja alguma opção de desambiguação. Nesse caso mande o exemplo mínimo para eu dar uma olhara.

**Comment by dbmrq** [comment]
Pronto, consertei as iniciais nos casos de desambiguação. Dê mais uma testada geral, por favor. Acho que agora está tudo certo:

```tex
\documentclass{article}
\usepackage{lmodern}
\usepackage[style=abnt, giveninits, uniquename=init, sccite, scbib]{biblatex}

\usepackage{filecontents}
\begin{filecontents*}{\jobname.bib}
  @book{test,
    title = {teste},
    author = {John Smith and Jane Smith and John Doe and Edward Doe},
  }
  @book{test2,
    title = {teste},
    author = {John Doe and Edward Doe and John Smith},
  }
\end{filecontents*}

\addbibresource{\jobname.bib}

\begin{document}
  \cite{test}
  \cite{test2}
  \printbibliography
\end{document}
```

<img width="778" alt="captura de tela 2017-10-14 as 13 07 16" src="https://user-images.githubusercontent.com/15813674/31577193-ab1f7e3c-b0e0-11e7-88c8-bac6db54ce73.png">

**Comment by mvlp** [comment]
Exatamente, era o caso de desambiguação. 
Entretanto, segundo a NBR 10520:2002, ítem 6.1.2 tem a indicação de que o prenome na desambiguação deve ser colocado na frente do sobrenome e separado por vírgula.



      De: Daniel Marques <notifications@github.com>
 Para: abntex/biblatex-abnt <biblatex-abnt@noreply.github.com> 
Cc: mvlp <marcos_vlp@yahoo.com.br>; Mention <mention@noreply.github.com>
 Enviadas: Sábado, 14 de Outubro de 2017 13:08
 Assunto: Re: [abntex/biblatex-abnt] Citações com múltiplos artigos com múltiplos autores (#26)
   
Pronto, consertei as iniciais nos casos de desambiguação. Dê mais uma testada geral, por favor. Acho que agora está tudo certo:\documentclass{article}
\usepackage{lmodern}
\usepackage[style=abnt, giveninits, uniquename=init, sccite, scbib]{biblatex}

\usepackage{filecontents}
\begin{filecontents*}{\jobname.bib}
  @book{test,
    title = {teste},
    author = {John Smith and Jane Smith and John Doe and Edward Doe},
  }
  @book{test2,
    title = {teste},
    author = {John Doe and Edward Doe and John Smith},
  }
\end{filecontents*}

\addbibresource{\jobname.bib}

\begin{document}
  \cite{test}
  \cite{test2}
  \printbibliography
\end{document}—

**Comment by dbmrq** [comment]
@mvlp Bem observado! Já resolvi. :)

**Comment by mvlp** [comment]
Olá Daniel,Ótimo trabalho, obrigado pela paciência também.Percebi só um último detalhe que fiquei na dúvida.Citação indireta de 2 trabalhos do mesmo autor está se comportando assim:a) sem parênteses: AUTOR (1990) e AUTOR (1991)b) com parênteses: (AUTOR,1991;1992)
Não achei na norma uma informação clara a respeito da primeira opção.att,



      De: Daniel Marques <notifications@github.com>
 Para: abntex/biblatex-abnt <biblatex-abnt@noreply.github.com> 
Cc: mvlp <marcos_vlp@yahoo.com.br>; Mention <mention@noreply.github.com>
 Enviadas: Domingo, 15 de Outubro de 2017 14:39
 Assunto: Re: [abntex/biblatex-abnt] Citações com múltiplos artigos com múltiplos autores (#26)
   
@mvlp Bem observado! Já resolvi. :)—

**Comment by dbmrq** [comment]
Uhm, isso acontece mesmo se você usar `\textcites{entrada1, entrada2}`?
Nesse caso acho que está errado mesmo, vou dar uma olhada assim que
possível.

Em seg, 16 de out de 2017 às 09:11, mvlp <notifications@github.com>
escreveu:

**Comment by mvlp** [comment]
Sim, ocorre mesmo utilizando o \textcites{}.


      De: Daniel Marques <notifications@github.com>
 Para: abntex/biblatex-abnt <biblatex-abnt@noreply.github.com> 
Cc: mvlp <marcos_vlp@yahoo.com.br>; Mention <mention@noreply.github.com>
 Enviadas: Segunda-feira, 16 de Outubro de 2017 12:18
 Assunto: Re: [abntex/biblatex-abnt] Citações com múltiplos artigos com múltiplos autores (#26)
   
Uhm, isso acontece mesmo se você usar `\textcites{entrada1, entrada2}`?
Nesse caso acho que está errado mesmo, vou dar uma olhada assim que
possível.

Em seg, 16 de out de 2017 às 09:11, mvlp <notifications@github.com>
escreveu:

**Comment by dbmrq** [comment]
Pronto, *acho* que resolvi o problema. Tive que fazer uma mudança meio grande no código, então se você puder mais uma testada geral seria bom. Qualquer coisa me avisa.

Vou reabrir aqui só pra me lembrar de arrumar o manual, que não compila mais com a última atualização.

**Comment by mvlp** [comment]
Olá Daniel,
a) citação indireta sem parênteses: A separação dos anos de trabalhos de mesmo autor está feita com vírgula e não com ponto-e-vírgula. Ocorre uma ordenação crescente automática dos anos dos trabalhos. O nome do autor não tem hiperlink, somente no ano. Ex: Fulano (1950,1952) => deveria ser assim? => Fulano (1950;1952).
b) citação indireta com parênteses: percebi que você colocou a ordenação da citação de múltiplos trabalhos conforme a norma (em ordem alfabética). Porém quando existem dois trabalhos do mesmo autor em anos diferentes ele coloca o trabalho mais recente primeiro. Ex.: (CICLANO, 1990; FULANO, 2015; 1993) => deveria ser assim? => (CICLANO, 1990; FULANO, 1993; 2015)
att,

      De: Daniel Marques <notifications@github.com>
 Para: abntex/biblatex-abnt <biblatex-abnt@noreply.github.com> 
Cc: mvlp <marcos_vlp@yahoo.com.br>; Mention <mention@noreply.github.com>
 Enviadas: Terça-feira, 17 de Outubro de 2017 1:59
 Assunto: Re: [abntex/biblatex-abnt] Citações com múltiplos artigos com múltiplos autores (#26)
   
Pronto, acho que resolvi o problema. Tive que fazer uma mudança meio grande no código, então se você puder mais uma testada geral seria bom. Qualquer coisa me avisa.Vou reabrir aqui só pra me lembrar de arrumar o manual, que não compila mais com a última atualização.—

**Comment by dbmrq** [comment]
Pronto, acho que resolvi todos os problemas.

- O ponto e vírgula já estava aparecendo pra mim.

- As entradas agora são impressas na ordem em que o usuário as coloca. Elas estavam ordenadas por nome, título e ano, como na bibliografia. Isso não faz sentido nas citações e não é tão fácil usar uma ordem diferente pra cada caso. De qualquer forma eu acho que usar a ordem que o usuário colocou é o mais confiável e previsível, então vou deixar assim.

- Consertei o hyperlink dos nomes no \textcite.

Me avise se tiver mais algum problema. Obrigado pela ajuda e pela paciência testando. :)

**Comment by dbmrq** [comment]
@mvlp Atualizei a documentação e fechei este issue. Se você encontrar mais algum problema (ou fizer um exemplo mínimo com o problema do ponto e vírgula) abra um issue novo, por favor, assim fica mais organizado.
