### ISSUE TITLE
Formatação de citações e referências

### ISSUE THREAD

**Issue by mvlp** [abntex/biblatex-abnt#27]
Prezados,
Percebi as seguintes inconsistências nas citações/referências:
a) citações indiretas (\textcite{}):
    a.1) trabalhos de um mesmo autor e de anos diferentes estão separados por vírgula
    a.2) múltiplos trabalhos de 2 autores estão separados por vírgula e deveria ser por "e"
b) Na lista de referências os nomes/prenomes não aparecem em versalete. Quando utilizo apenas as iniciais tal problema não ocorre.
Segue um exemplo mínimo:
\documentclass{article}
\usepackage{lmodern}
\usepackage[style=abnt, language=brazil, sccite, scbib]{biblatex}

\usepackage{filecontents}

\begin{filecontents*}{\jobname.bib}	
	@Article{fama1993,
		Title                    = {Common risk factors in the returns on stocks and bonds},
		Author                   = {Eugene F. Fama and Kenneth R. French},
		Journal                  = {Journal of Financial Economics},
		Year                     = {1993},
		Number                   = {1},
		Pages                    = {3 - 56},
		Volume                   = {33},
	}
	@article{fama2015,
		title = "A five-factor asset pricing model",
		journal = "Journal of Financial Economics",
		volume = "116",
		number = "1",
		pages = "1 - 22",
		year = "2015",
		author = "Eugene F. Fama and Kenneth R. French"
	}
	@article{markowitz1952util,
		author = {Markowitz, Harry Max},
		title = {The Utility of Wealth},
		journal = {Journal of Political Economy},
		volume = {60},
		number = {2},
		pages = {151-158},
		year = {1952}	
	}
	@Article{markowitz1959,
		Title                    = {Portfolio selection: efficient diversification of investments},
		Author                   = {Markowitz, Harry Max},
		Journal                  = {Cowies Foundation Monograph},
		Year                     = {1959},
		Number                   = {16}
	}
	@article{markowitz1952,
		Title                    = {Portfolio Selection},
		Author                   = {Markowitz, Harry Max},
		Journal                  = {The Journal of Finance},
		Year                     = {1952},
		Number                   = {1},
		Pages                    = {77--91},
		Volume                   = {7},
		Publisher                = {Blackwell Publishing Ltd},
	}
\end{filecontents*}

\addbibresource{\jobname.bib}

\begin{document}
	\noindent\textcites{markowitz1952,markowitz1952util,markowitz1959,fama1993,fama2015}\\
	\cites{markowitz1952,markowitz1952util,markowitz1959,fama1993,fama2015}\\
	\printbibliography
\end{document}

grato pela atenção,
att,
Marcos

**Comment by dbmrq** [comment]
Pronto, acredito que resolvi os problemas do item "a". Dê mais uma olhada, por favor.

Quanto ao item "b", acho que esse é o comportamento adequado mesmo. A ABNT pede que só o sobrenome seja impresso em maiúsculas. O uso de versalete já está fora da norma, então até temos alguma liberdade para fazer o que quisermos aí, mas o versalete tem a função de substituir o uso de maiúsculas no texto corrente, e os prenomes não devem estar em maiúsculas, então, na minha opinião, também não devem estar em versalete.

Além disso, acho que o ponto de colocar os sobrenomes em maiúsculas é destacar as chaves das citações. Quando você cita um autor aparece "FULANO" em maiúsculas, aí você vai procurar na bibliografia e está lá outra vez "FULANO", de modo que fica mais fácil encontrar a entrada adequada. Já os prenomes não precisam ser destacados, pelo contrário, isso só atrapalharia. Por esse motivo é que, mesmo usando iniciais, a inicial do prenome não estava em versalete. A inicial por si só, contudo, é uma letra maiúscula, então até faz algum sentido mantê-la em versalete com o sobrenome, e eu concordo que fica mais bonito, então aceitei a sugestão. Quando é usado o prenome inteiro, por outro lado, acho que isso não se aplica.

**Comment by dbmrq** [comment]
@mvlp Você chegou a testar, está tudo certo? Se você puder, dá mais uma olhada e me fala. Se não tiver mais nenhum problema vou enviar a atualização pro ctan.

**Comment by mvlp** [comment]
@dbmrq Acabei abrindo outra issue
