### ISSUE TITLE
Citações indiretas separadas por "e"

### ISSUE THREAD

**Issue by mvlp** [abntex/biblatex-abnt#28]
Detectei que as citações indiretas sem parênteses estão separadas somente por "e", talvez por causa de uma correção de bug anterior.
Segue o exemplo mínimo:

\documentclass{article}
\usepackage{lmodern}
\usepackage[style=abnt, language=brazil, sccite, scbib]{biblatex}

\usepackage{filecontents}

\begin{filecontents*}{\jobname.bib}	
	@Article{fama1993,
		Title                    = {Common risk factors in the returns on stocks and bonds},
		Author                   = {Eugene F. Fama and Kenneth R. French},
		Journal                  = {Journal of Financial Economics},
		Year                     = {1993},
		Number                   = {1},
		Pages                    = {3 - 56},
		Volume                   = {33},
	}
	@article{fama2015,
		title = "A five-factor asset pricing model",
		journal = "Journal of Financial Economics",
		volume = "116",
		number = "1",
		pages = "1 - 22",
		year = "2015",
		author = "Eugene F. Fama and Kenneth R. French"
	}
	@article{markowitz1952util,
		author = {Markowitz, Harry Max},
		title = {The Utility of Wealth},
		journal = {Journal of Political Economy},
		volume = {60},
		number = {2},
		pages = {151-158},
		year = {1952}	
	}
	@Article{markowitz1959,
		Title                    = {Portfolio selection: efficient diversification of investments},
		Author                   = {Markowitz, Harry Max},
		Journal                  = {Cowies Foundation Monograph},
		Year                     = {1959},
		Number                   = {16}
	}
	@article{markowitz1952,
		Title                    = {Portfolio Selection},
		Author                   = {Markowitz, Harry Max},
		Journal                  = {The Journal of Finance},
		Year                     = {1952},
		Number                   = {1},
		Pages                    = {77--91},
		Volume                   = {7},
		Publisher                = {Blackwell Publishing Ltd},
	}
	@article{tversky1973availability,
		title={Availability: A heuristic for judging frequency and probability},
		author={Tversky, Amos and Kahneman, Daniel},
		journal={Cognitive psychology},
		volume={5},
		number={2},
		pages={207--232},
		year={1973},
		publisher={Elsevier}
	}
	@article{bs1973,
		author = {Fischer Black and Myron Scholes},
		journal = {Journal of Political Economy},
		number = {3},
		pages = {637-654},
		publisher = {University of Chicago Press},
		title = {The Pricing of Options and Corporate Liabilities},
		volume = {81},
		year = {1973}
	}
\end{filecontents*}

\addbibresource{\jobname.bib}

\begin{document}
	\noindent\textcites{bs1973,markowitz1952,markowitz1952util,markowitz1959,fama1993,fama2015}\\
	\cites{bs1973,markowitz1952,markowitz1952util,markowitz1959,fama1993,fama2015}\\
	\printbibliography
\end{document}

att,
Marcos

**Comment by dbmrq** [comment]
Pronto, espero não ter quebrado mais nada, rs.
Se tiver mais algum problema pode abrir outros issues. Muito obrigado pela ajuda. :)

**Comment by mvlp** [comment]
Parece que está tudo ok agora.
Disponha.

**Comment by mvlp** [comment]
Testei com a versão 3.1, mas percebi que trabalhos de múltiplos autores voltaram a não ser agrupados.

**Comment by dbmrq** [comment]
Ah, isso não está arrumado na versão 3.1. Você pode usar este commit: https://github.com/abntex/biblatex-abnt/commit/df15983bc459a278f01c9333b866f8a1b0503830

**Comment by dbmrq** [comment]
(https://github.com/abntex/biblatex-abnt/archive/df15983bc459a278f01c9333b866f8a1b0503830.zip)
