### ISSUE TITLE
Nome de organizações nas referências

### ISSUE THREAD

**Issue by mvlp** [abntex/biblatex-abnt#29]
Percebi algo estranho ao cita organizações quando o versalete está habilitado juntamente com o giveinits. As primeiras letras do nome completo da organização aparecem maiores que as demais letras na lista de referências. Sem utilizar o giveinits o comportamento é diferente.

\documentclass{article}
\usepackage[T1]{fontenc}		% Selecao de codigos de fonte.
\usepackage[utf8]{inputenc}		% Codificacao do documento (conversão automática dos acentos)
\usepackage{lmodern}
\usepackage[style=abnt, language=brazil, scbib, giveninits]{biblatex}
%\usepackage[style=abnt, language=brazil, scbib]{biblatex}

\usepackage{filecontents}

\begin{filecontents*}{\jobname.bib}	
	@book{bodie2014,
		title={Investments},
		author={Zvi Bodie and Alex Kane and Alan J. Marcus},
		year={2014},
		edition={10},
		publisher={McGraw-Hill/Irwin}
	}
	@manual{NBR105202002,
		address = {Rio de Janeiro},
		month = {8},
		org-short = {ABNT},
		organization = {Associa{\c c}{\~ a}o Brasileira de Normas T{\'e}cnicas},
		pages = {7},
		subtitle = {Informa{\c c}{\~a}o e documenta{\c c}{\~a}o --- Apresenta{\c c}{\~a}o de cita{\c c}{\~o}es em documentos},
		title = {{NBR} 10520},
		year = {2002}
	}
@techreport{anbima2017,
	title        = {Consolidado Histórico de Fundos de Investimento},
	organization = {Associação Brasileira das Entidades dos Mercados Financeiro e de Capitais},
	org-short  = {ANBIMA},
	year         = 2017,
	url = {http://www.anbima.com.br/pt_br/informar/estatisticas/fundos-de-investimento/fi-consolidado-historico.htm}
}
\end{filecontents*}

\addbibresource{\jobname.bib}

\begin{document}
	\noindent\textcite{bodie2014,NBR105202002,anbima2017}\\
	\cite{NBR105202002,anbima2017}\\
	\printbibliography
\end{document}

**Comment by dbmrq** [comment]
O BibLaTeX usa os campos `author` e `shortauthor` mesmo para "autores corporativos":

<img width="668" alt="captura de tela 2017-10-21 as 12 47 10" src="https://user-images.githubusercontent.com/15813674/31852844-10cbefa4-b65e-11e7-8c0a-ee264f81a7a9.png">

Para facilitar a transição entre o `abntex2cite` e o `biblatex-abnt`, eu criei os campos `organization`, `org-short` e outros, mas está cada vez mais difícil adicionar novos recursos e ao mesmo tempo manter essas facilidades. Já tirei do manual a seção que falava da compatibilidade entre os dois pacotes, que estava ficando desatualizada, e nas próximas versões pretendo levar cada vez menos em conta essas peculiaridades do `abntex2cite`.

Usando o formato do BibLaTeX, o exemplo funciona direitinho:

```tex
\documentclass{article}
\usepackage[T1]{fontenc}	% Selecao de codigos de fonte.
\usepackage[utf8]{inputenc}	% Codificacao do documento (conversão automática dos acentos)
\usepackage{lmodern}
\usepackage[style=abnt, language=brazil, scbib, giveninits, uniquename=init]{biblatex}
%\usepackage[style=abnt, language=brazil, scbib]{biblatex}

\usepackage{filecontents}

\begin{filecontents*}{\jobname.bib}
@book{bodie2014,
title={Investments},
author={Zvi Bodie and Alex Kane and Alan J. Marcus},
year={2014},
edition={10},
publisher={McGraw-Hill/Irwin}
}
@Manual{NBR105202002,
address = {Rio de Janeiro},
month = {8},
org-short = {ABNT},
author = {{Associa\c{c}\~ao Brasileira de Normas T\'ecnicas}},
pages = {7},
subtitle = {Informa{\c c}{~a}o e documenta{\c c}{~a}o --- Apresenta{\c c}{~a}o de cita{\c c}{~o}es em documentos},
title = {{NBR} 10520},
year = {2002}
}
@techreport{anbima2017,
title = {Consolidado Histórico de Fundos de Investimento},
author = {{Associação Brasileira das Entidades dos Mercados Financeiro e de Capitais}},
org-short = {ANBIMA},
year = 2017,
url = {http://www.anbima.com.br/pt_br/informar/estatisticas/fundos-de-investimento/fi-consolidado-historico.htm}
}
\end{filecontents*}

\addbibresource{\jobname.bib}

\begin{document}
\noindent\textcite{bodie2014,NBR105202002,anbima2017}\\
\cite{NBR105202002,anbima2017}\\
\printbibliography
\end{document}
```

<img width="442" alt="captura de tela 2017-10-21 as 12 54 48" src="https://user-images.githubusercontent.com/15813674/31852936-0ecf25e4-b65f-11e7-9686-faeb944424b7.png">
