### ISSUE TITLE
Anos de trabalhos de mesmo autor devem ser separados por vírgula

### ISSUE THREAD

**Issue by mvlp** [abntex/biblatex-abnt#30]
A separação dos anos dos trabalhos de mesmo autor está com ";".
NBR 10520 - ítem 6.1.4

**Comment by dbmrq** [comment]
Uhm, tem razão. Quando eu comecei a escrever o `biblatex-abnt` não sabia tanto sobre o BibLaTeX, tem vários probleminhas, como você percebeu, rs. Vou parar de ser preguiçoso e reescrever o estilo de citação do zero, e vou ver também se consigo incluir a NBR 10520 no arquivo `abnt-testcase`, assim vai ficar mais fácil testar a formatação e não vamos precisar ficar tapando buracos. Obrigado pela ajuda. :)

**Comment by mvlp** [comment]
Disponha @dbmrq .
Por favor não abandone o biblatex, pois migrar pra outros estilos tipo apa fica muito mais fácil depois.
Eu verifiquei que a norma abnt é baseada na  ISO 690, normalmente eles não alteram quase nada. Talvez seja um ponto de partida melhor caso você queira reescrever algo.
att,

**Comment by dbmrq** [comment]
Pode deixar, eu uso o BibLaTeX praticamente todo dia, mesmo se eu quiser não vou poder abandonar-lo, rs.

Dei uma boa reformulada no estilo de citação, acho que agora ele vai funcionar melhor e também vai ser mais fácil de arrumar os problemas que aparecerem.

Eu acrescentei, no diretório `doc/tests`, o arquivo [`NBR10520-2002.tex`](https://github.com/abntex/biblatex-abnt/blob/master/doc/tests/NBR10520-2002.tex), que imprime todas as citações mencionadas na NBR 10520. Assim vai ficar bem mais fácil de testar o estilo; é só recompilar esse arquivo e compará-lo com a norma pra ver se não tem nada de errado. Acabei de fazer isso e por enquanto está tudo certo. 🎉 

Esse arquivo só imprime, contudo, o que está de fato na norma, então opções apócrifas, como as de versalete, têm de ser testadas individualmente. Os casos previstos pela norma, como eu disse, estão funcionando corretamente, mas eu mudei quase todo o estilo de citação, então talvez ainda tenha algum probleminha no uso dessas opções extras. Se você encontrar alguma coisa me avise, por favor. :)
