### ISSUE TITLE
Problemas na instalação

### ISSUE THREAD

**Issue by HugoFarias** [abntex/biblatex-abnt#31]
Agradeço desde já se puder me ajudar.
Instalei o TexLive 2016, através de um PPA, no Ubuntu 16.04. Não conseguindo usar o biblatex-abnt (o estilo abnt não era encontrado), tentei o processo de instalação manual. Agora ele encontra o estilo, mas não gera a referência. Como teste, conforme a figura, tentei compilar o manual.

![captura de tela de 2017-10-30 17-14-55](https://user-images.githubusercontent.com/8578628/32190729-e29a6f40-bd95-11e7-9fe7-3523a8b83049.png)

Desde já muito obrigado!

**Comment by dbmrq** [comment]
Eu não tenho muita experiência com Linux, mas, na pouca que tenho, nunca consegui fazer o TeX funcionar direito usando gerenciadores de pacotes, só com o instalador do TeX Live mesmo.

Cheque se a instalação manual está no diretório `texmf` certo e se o banco de dados está atualizado – você rodou o `texhash` ou algo parecido?

Se mesmo assim não dar certo, o que eu faria no seu lugar é desinstalar sua versão atual e usar o instalador do TeX Live, mas não sei se esse é o ideal ou se é só burrice minha mesmo, rs.

Em último caso, você também pode sempre colocar os arquivos do estilo no próprio diretório do documento .tex que está compilando, mas é inconveniente, e, de qualquer forma, acho importante você ter acesso ao seu diretório `texmf` local.

Desculpe não ajudar mais. Você também pode pedir ajuda no [grupo LaTeX Br](https://groups.google.com/forum/m/#!forum/latex-br), eles devem saber mais do que eu. Por enquanto vou fechar esta issue, já que não é um problema com o biblatex-abnt.

**Comment by HugoFarias** [comment]
Descobri, por fim, o problema. Respondo pro caso de outro cometer o mesmo erro.

Não estive atento aos requisitos mínimos. A solução foi instalá-los à parte, porque os do TexLive estão desatualizados, para só então instalar o biblatex-abnt.

**Comment by edusantana** [comment]
@dbmrq Se você quiser posso auxiliar na criação de testes automatizados para serem realizados por um servidor de integração contínua (travis) com o linux e talvez o osx também.

A ideia é que toda vez que você faça um push, o servidor identifica, baixa o textlive e instala. Depois atualiza o biblatex-abnt a partir do github e realiza os testes.

Eu fiz para o [limarka](https://travis-ci.org/abntex/limarka/builds).

**Comment by dbmrq** [comment]
@edusantana Abri a issue #33 pra falarmos disso. :)
