### ISSUE TITLE
Erro de compilação

### ISSUE THREAD

**Issue by mvlp** [abntex/biblatex-abnt#32]
Não consigo usar, testei com exemplo mínimo e dá o erro:

LaTeX error: "kernel/command-not-defined" Control sequence \regex_match:nnTF undefined. For immediate help type H <return>. ...erate_variant:Nn \regex_match:nnTF { nV }

Ele aponta pra linha 438 do abnt.bbx

**Comment by edusantana** [comment]
@mvlp você poderia fornecer o exemplo mínimo que testou? Qual o sistema que você utiliza?

**Comment by dbmrq** [comment]
Rodando o script [test.sh](https://github.com/abntex/biblatex-abnt/blob/master/tests/test.sh) todas as entradas são compiladas direitinho e sem erros. Veja se não está faltando nenhum pacote necessário na sua instalação (e.g., o expl3) e tente compilar os exemplos disponíveis no diretório [tests](https://github.com/abntex/biblatex-abnt/tree/master/tests), ou ao menos mande um exemplo mínimo que reproduza o problema.

**Comment by dbmrq** [comment]
Por enquanto vou fechar esta issue então. Qualquer coisa pode avisar aqui.

**Comment by mvlp** [comment]
Perdão, descobri que o biber do meu ubuntu linux ainda está no 2.7, provavelmente o biblatex também está fora dos requisitos. Deu erro de compilação no test.sh também, provavelmente devido à isso.

**Comment by dbmrq** [comment]
Sem problemas. Houve alguns problemas ao enviar as atualizações do BibLaTeX e do Biber, então as atualizações estão meio inconsistentes. Se for necessário, esses pacotes também podem ser instalados manualmente (as instruções pro BibLaTeX está no repositório aqui no Github e o Biber pode ser baixado no Sourceforge). Outra possibilidade é baixar o biblatex-abnt 3.1 aqui nos “Releases”.
