### ISSUE TITLE
Adicionar servidor de integração contínua

### ISSUE THREAD

**Issue by dbmrq** [abntex/biblatex-abnt#33]
@edusantana Abri uma issue nova pra falarmos dos testes. Se você puder ajudar eu agradeço! Meu plano era eventualmente fazer isso mesmo, mas nunca usei o Travis e ainda não tive tempo de ir atrás.

Uma coisa muito legal seria testar inclusive se o estilo continua adequado às normas da ABNT. É mais fácil do que parece… o diretório [tests](https://github.com/abntex/biblatex-abnt/tree/master/tests) já contém um script que compara os arquivos de referência (checados manualmente) a arquivos gerados usando a versão atual do estilo. As diferenças aparecem em vermelho, e dá pra checar isso usando o Ghostscript. Se você rodar o [test.sh](https://github.com/abntex/biblatex-abnt/blob/master/tests/test.sh) e depois fizer `gs -o - -sDEVICE=inkcov NBR10520-2002_test.pdf`, por exemplo, o resultado é:

```
Page 1
 0.00000  0.00105  0.00105  0.00651 CMYK OK
Page 2
 0.00000  0.00000  0.00000  0.03465 CMYK OK
Page 3
 0.00000  0.00000  0.00000  0.03232 CMYK OK
Page 4
 0.00000  0.00000  0.00000  0.02739 CMYK OK
```

Ou seja, a primeira página tem amarelo e magenta, porque o título e a data são diferentes:

<img width="413" alt="captura de tela 2017-11-26 as 18 26 02" src="https://user-images.githubusercontent.com/15813674/33244023-4c7c699e-d2d7-11e7-973b-14b7bf569bad.png">

Mas as páginas 2, 3 e 4 só contêm preto, portanto a última versão do biblatex-abnt continua adequada às normas.

Imagino que o Travis também possa automatizar isso, então se uma nova versão do biblatex-abnt se distanciar das normas ficaríamos sabendo imediatamente.

**Comment by edusantana** [comment]
Como realizar instalação manual a partir do github?

**Comment by dbmrq** [comment]
É só copiar os arquivos pro diretório `texmf` local e rodar o `texhash`. Pode inclusive clonar o repositório todo, vai ter arquivos desnecessários junto, mas tudo bem.

**Comment by dbmrq** [comment]
Atualizei o script de teste pra fazer o que eu disse, e agora ele só retorna 0 quando tá tudo certo.

Uma vez que o Travis estiver no ar não deve ser difícil ele rodar e checar o resultado também. Se eu puder fazer mais alguma coisa me avisa. :)

**Comment by edusantana** [comment]
Ok, suponho que seja  o `/usr/local/texlive/2017/texmf-dist/tex/latex/biblatex-abnt` com o texlive...

**Comment by edusantana** [comment]
```bash
# ./test.sh
Running tests...
sed: can't read s/\\toggletrue{reference}/% \\toggletrue{reference}/: No such file or directory
sed: can't read s/\\toggletrue{reference}/% \\toggletrue{reference}/: No such file or directory
rm: cannot remove 'NBR10520-2002.bbl': No such file or directory
rm: cannot remove 'NBR6023-2002.bbl': No such file or directory
sed: can't read s/% \\toggletrue{reference}/\\toggletrue{reference}/: No such file or directory
sed: can't read s/% \\toggletrue{reference}/\\toggletrue{reference}/: No such file or directory
./test.sh: line 42: gs: command not found
./test.sh: line 51: gs: command not found
ALL GOOD!
# 
```

**Comment by edusantana** [comment]
Se você quiser testar:

1. Instalar o [docker](https://docs.docker.com/engine/installation/)
2. `docker pull edusantana/ruby-latex-full` (baixa imagem com o linux, ruby e texlive-2017 completo)
3. `git clone https://github.com/abntex/biblatex-abnt`
4. `rm -rf /usr/local/texlive/2017/texmf-dist/tex/latex/biblatex-abnt`
5. `cd /usr/local/texlive/2017/texmf-dist/tex/latex/`
6. `ln -s ~/biblatex-abnt`
7. `/root/biblatex-abnt/tests`
8. `./test.sh`

**Comment by dbmrq** [comment]
Obrigado!

O diretório que você citou é o geral eu acho. O local no linux se não me engano é `~/texmf`.

E os erros no script parecem ser porque ele está sendo rodado num diretório diferente do original (onde estão os outros arquivos necessários).

Mas já ajudou bastante. Mais tarde eu dou uma olhada, quando puder. :)

**Comment by dbmrq** [comment]
Ah, além disso acho que o `sed` funciona diferente no mac e no linux, pode estar errado no script por isso. Assim que eu conseguir tento arrumar.

**Comment by dbmrq** [comment]
Ah, e além disso o `gs` não está funcionando porque deve precisar instalar o Ghostscript.

**Comment by dbmrq** [comment]
```
~ > docker pull edusantana/ruby-latex-full
Using default tag: latest
Error response from daemon: pull access denied for edusantana/ruby-latex-full, repository does not exist or may require 'docker login'
```

**Comment by dbmrq** [comment]
De qualquer forma arrumei o `sed`, então imagino que instalando o Ghostscript deve funcionar agora.

**Comment by edusantana** [comment]
Depois de instalar o ghostscript deu o seguinte erro:

```bash
# ./test.sh
Running tests...
sed: -e expression #1, char 1: unknown command: `.'
# gs --version
9.06
# 
```

Tenta criar o login no docker e executar novamente, eu atualizei as instruções aí acima.

OBS: O container do docker não é ubuntu, é debian.

**Comment by edusantana** [comment]
O arquivo do `test.sh` me pareceu um pouco complexo. Pode ser que seja uma pergunta besta, mas não seria melhorar comparar apenas os textos do pdfs?

No limarka eu invoco o `pdftotext` para gerar o conteúdo txt e comparo o resultado: [neste exemplo eu verifico que a seção do anexo está sendo gerada no formato da abnt, com letras](https://github.com/abntex/limarka/blob/master/spec/anexos_spec.rb#L76-L81).

**Comment by dbmrq** [comment]
Esse erro acontece mesmo fazendo login. Puxar outras imagens funciona.

```
~ > docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (dbmrq): dbmrq
Password: 
Login Succeeded
~ > docker pull edusantana/ruby-latex-full
Using default tag: latest
Error response from daemon: pull access denied for edusantana/ruby-latex-full, repository does not exist or may require 'docker login'
```

Mas eu fiz mais uma mudança no script e acho que *agora* vai funcionar, rs. Você pode tentar outra vez?

Sobre comparar só o texto, perderíamos a formatação, então não daria pra garantir que os trechos certos estão em itálico/negrito, e também tem outros elementos que não são *texto*, como espaços que podem ser maiores ou menores, ou os traços sublinhares que substituem autores e títulos repetidos. Além disso eu não criei um arquivo de referência, mas poderíamos testar inclusive se está tudo certo usando as opções de versalete, e por aí vai. Acho que é um método mais garantido, podemos ter certeza de que não mudou absolutamente nada, e ver facilmente o que mudou.

**Comment by edusantana** [comment]
```
# ./test.sh
Running tests...
# 
```

Não teve nenhum output. É assim mesmo?

Utilize `edusantana/limarka`, atualizei as instruções.

**Comment by dbmrq** [comment]
Demora um pouco, mas depois de um tempo deveria sair o resultado.

Você também pode tentar compilar os arquivos tex do diretório tests
individualmente pra ver se pode estar faltando algum pacote ou algo assim.

À noite eu tento de novo o Docker.

**Comment by edusantana** [comment]
> Sobre comparar só o texto, perderíamos a formatação, então não daria pra garantir que os trechos certos estão em itálico/negrito, 

Estou divagando, ok? Que tal verificar os arquivos intermediários que são gerados?

Eu vou auxiliar implementar os testes conforme você achar melhor para manter o repositório... se a estratégia for utilizar o `gs` tudo bem!

Recomendo verificar as estratégias de testes de projetos similares.

**Comment by dbmrq** [comment]
Agora deu certo! Fiz o teste aqui e o problema era que o BibLaTeX e o Biber estavam desatualizados. Se você fizer `tlmgr update --self --all` antes do passo 6 funciona tudo direitinho.

Quanto ao teste, comparar os arquivos intermediários é uma possibilidade, mas ainda acho ela inferior por alguns motivos:

1. Não me prece ser mais fácil. Há múltiplos arquivos envolvidos, teríamos que identificar as partes relevantes de cada um deles, extraí-las e compará-las. Além disso, o pdf pode ser diretamente comparado à norma (por um ser humano), então podemos manter só ele como referência. Já os arquivos intermediários não podem ser comparados à norma sem o pdf, então teríamos que manter como referência tanto os pdfs quando esses arquivos, deixando tudo mais confuso e aumentando o número de lugares onde algo pode dar errado.
2. De uma versão pra outra o BibLaTeX pode usar macros diferentes pra chegar aos mesmos resultados. Elas podem ser expandidas em momentos diferentes, o Biber pode mudar partes relevantes dos arquivos bbl... sei lá. Enfim, quando os arquivos intermediários mudassem o teste falharia ainda que o resultado final continuasse correto. O que interessa pra gente é o resultado final, então acho que o mais seguro vai ser sempre comparar justamente o resultado final.
3. Quando o teste falhar, o método atual permite ver exatamente o que está errado e onde. É só abrir o pdf resultante e as diferenças aparecem em vermelho. Comparando os arquivos intermediários esse processo seria bem mais chato.

Sobre as estratégias de projetos similares, não conheço nenhum estilo de BibLaTeX que tenha testes para checar a adequação às normas. Mas no caso de projetos em LaTeX como um todo, as duas possibilidades são válidas. Veja, por exemplo, esta questão: https://tex.stackexchange.com/a/12105
Você está propondo usar a primeira opção, eu estou usando a segunda, e a terceira é inviável nesse caso.

Se você ainda acha melhor usar os arquivos intermediários e quiser enviar um exemplo, eu estou disposto a considerá-lo, é claro, mas me parece que o método atual é mais simples e melhor. O script `test.sh` deve estar realmente confuso e ineficiente, mas isso é culpa da minha falta de habilidade com shell script, não com o teste em si, rs.

**Comment by edusantana** [comment]
Geralmente com os testes automatizados:

- [precisamos de um script ou similar que retorne um código de ERRO ou Sucesso](https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step). Seu script test.sh precisa retornar [algum Código de erro ou 0 quando finalizar com sucesso](http://linuxcommand.org/lc3_wss0140.php).

**Comment by edusantana** [comment]
Eu vi que seu script já retorna os erros, então vou configurar o teste.

**Comment by edusantana** [comment]
[Eu ainda não sei como configurar o travis com o `docker`](https://docs.travis-ci.com/user/docker/), então estou fazendo o jeito tradicional.

**Comment by edusantana** [comment]
Em caso do test falhar, você quer visualizar quais logs ou arquivos?

**Comment by edusantana** [comment]
É possível [fazer o teste rodar no OSX também](https://docs.travis-ci.com/user/multi-os/).

**Comment by dbmrq** [comment]
O ideal seria primeiro testar uma compilação qualquer pra ver se tem algum erro com o código em si ou com a compatibilidade entre o estilo e o BibLaTeX/Biber. Se esse teste falhasse teríamos que ver o arquivo .log resultante da compilação.

Se o primeiro teste passasse, então passaríamos pro teste atual, pra ver se, além de estar funcionando, o estilo está adequado às normas. Se esse segundo teste falhasse, teríamos que ver os arquivos compilados, NBR10520-2002_test.pdf e NBR6023-2002_test.pdf.

Acho que poderíamos juntar esses dois passos no mesmo script. O `test.sh` já compila os arquivos, então só precisamos saber se a falha foi na compilação ou na comparação. Talvez possamos retornar um exit code diferente no caso de falha na comparação, só não sei bem qual, não consegui descobrir que códigos são usados pelo latex. Mas podemos tentar algo como `3`, por exemplo. Então se o código for `0` está tudo certo, se for `3` o estilo não está adequado à norma e temos que ver os pdfs, e se o código for qualquer outro a compilação falhou, então temos que ver o log.

---

Sobre o erro que você citou [aqui](https://github.com/abntex/biblatex-abnt/issues/34#issuecomment-347542509), acho que o problema deve ser que o `sudo` usa um PATH diferente daquele do usuário. Olha só: https://unix.stackexchange.com/q/83191/176794

Então em vez de só `sudo tlmgr` você pode tentar algo assim: `sudo env "PATH=$PATH" tlmgr update --self --all`.

**Comment by edusantana** [comment]
@dbmrq o(s) teste(s) está(ão) passando na branch `travis`.

- Você faz o merge?
- Vai precisar de mais alguma coisa?

**Comment by dbmrq** [comment]
Ah, legal, muito obrigado pela ajuda! 🎉

Ainda é preciso fazer o que eu disse, criar códigos diferentes para o erro na compilação dos arquivos tex e para a comparação dos pdfs, mas eu posso fazer isso. E depois eu faço o merge sim. Tem algum jeito de testar as mudanças no `.travis.yml` sem ficar enviando commits aqui?

E sobre a issue #34, desculpe se eu pareci fechado à sugestão, só realmente não entendi qual seria a vantagem. Mas se você achar que vale a pena e quiser escrever o teste em ruby eu estou disposto a ser convencido. :)

**Comment by edusantana** [comment]
> Tem algum jeito de testar as mudanças no .travis.yml sem ficar enviando commits aqui?

Se para cá, você quis dizem o github, não. O travis é iniciado sempre que detecta um push ao repositósio.

Se para cá você quiser dizer esse issue, sim. Basta quando fizer o commit não indicar o número do issue na mensagem de commit. Mas a boa prática rege que todo commit deveria está relacionado a um issue. E a rastreabilidade é realizada exatamente através do número do commit na mensagem `#33`.

**Comment by dbmrq** [comment]
Quis dizer pro Github mesmo. Ok então, quando eu tiver tempo vou fazer os últimos ajustes e faço o merge. Obrigado!

**Comment by dbmrq** [comment]
Esqueci de citar o issue no commit, mas já fiz o merge e parece estar tudo certo. 🍾 

Obrigado mais uma vez!

Vou deixar a issue #34 aberta até definirmos o que fazer.

**Comment by edusantana** [comment]
Como agora você está utilizando a instalação local do texlive, talvez não precise mais usar o sudo env.

https://github.com/abntex/biblatex-abnt/blob/a2bc37004408fe4d38d372e78e53e20f28862e7b/tests/texlive.sh#L7-L25

**Comment by dbmrq** [comment]
Bem lembrado, vou tentar.

**Comment by dbmrq** [comment]
Sou incapaz de lembrar de citar o issue nos commits, rs., mas deu certo, valeu. :)

Instalando o TeX Live com `scheme-minimal` os testes estão demorando uns 2 minutos pra completar (em vez de 20), e com o Travis rodando sem sudo eles começam bem mais rápido. Não sei se você liga, mas daria pra fazer isso no limarka também. A última instalação do TeX Live lá demorou 846,9 segundos, a do biblatex-abnt demorou 53,5. Só teria que ver exatamente que pacotes você está usando.

**Comment by edusantana** [comment]
@dbmrq eu tinha vista suas alterações. Mas o problema é que o limarka depende do abntex2, que depende de um bocado de outras coisas. Para fazer uma instalação mínima e customizada do limarka iria demorar muito tempo procurando as dependências exatas.

Acho que vou cadastrar um issue com o label `help wanted`, daí se aparecer alguma alma caridosa...

Mas eu também estou pensando em mudar os testes para usar docker, ainda não testei no travis. espero que fique mais rápido.

**Comment by dbmrq** [comment]
É, o abntex2 é chato.

Fiz um teste rápido e consegui compilar o arquivo [xxx-Monografia.tex](https://github.com/abntex/limarka/blob/master/spec/latex/exemplo-minimo/xxx-Monografia.tex) usando a mesma instalação aqui do [texlive.sh](https://github.com/abntex/biblatex-abnt/blob/master/tests/texlive.sh) e mais:

    tlmgr install memoir textcase tools pdfpages abntex2 enumitem lastpage lipsum

Não sei se é o suficiente pra tudo o que você precisa, mas já deve ser um começo.

E parece que usando `sudo: false`, como eu fiz aqui, os testes já são rodados usando Docker:

> When specifying sudo: false, Travis CI runs each build in a container on a shared host via Docker. The container contents are a pristine copy of the Docker image, as guaranteed by Docker itself.
> 
> The advantage of running with sudo: false is dramatically reduced time between commit push to GitHub and the start of a job on Travis CI, which works especially well when one’s average job duration is under 3 minutes.

(https://docs.travis-ci.com/user/reference/trusty/#Container-based-with-sudo%3A-false)

Mas não sei se você precisa do `sudo` nos seus testes.
