### ISSUE TITLE
Warning ao importar babel

### ISSUE THREAD

**Issue by bismarckjunior** [abntex/biblatex-abnt#35]
Mensagem de aviso quando faço:

`\usepackage[brazilian, american]{babel}`

Aviso:

> Package biblatex Warning: File 'american-abnt.lbx' not found!(biblatex)                Ignoring mapping 'american' -> 'american-abnt'.

**Comment by dbmrq** [comment]
Oi, Bismarck.

O problema deve estar resolvido nesse último commit. Você vai ter que fazer a instalação manual pra usá-lo.

Ou então você pode usar `english` como idioma, em vez de `american`. Isso já era possível desde antes. Eu não tinha acrescentado as variantes específicas (`american`, `british`, `canadian`, `australian`) porque não olhei se é necessária alguma mudança ortográfica, mas acredito que não, e essas opções também alteram o uso da pontuação e tal, então achei melhor acrescentá-las logo. Só fique de olho nisso, a mesma tradução está sendo usada para todas as variantes, então me avise se você perceber algo que deveria estar diferente.

**Comment by dimicamp** [comment]
Olá. Daniel, primeiramente, meus cumprimentos pelo excelente trabalho. Achei este tópico ao procurar no google por "Package biblatex Warning: File 'brazilian-abnt-abnt.lbx' not found!"

Este warning não acontecia anteriormente, mas ao fazer uma atualização do MikTex e seus pacotes, passou a acontecer.  A lista de pacotes que estou usando está a seguir. 

\usepackage[latin1]{inputenc}
\usepackage[hyphens]{url}
\usepackage[brazil]{babel}
\usepackage{csquotes}
\usepackage{xpatch}
\usepackage[backend=biber,language=auto,hyperref=true,style=abnt,justify,repeatfields,indent]{biblatex}
\usepackage{units}
\usepackage{acronym}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{latexsym}
\usepackage{graphicx}
\usepackage{listings}
\usepackage{fancyvrb}
\usepackage{longtable}
\usepackage{colortbl}
\usepackage{multirow}
\usepackage{multicol}
\usepackage{color}
\usepackage{subfigure}
\usepackage{caption}
\usepackage{indentfirst}
\usepackage[pdfpagelabels]{hyperref}
\usepackage[shortlabels]{enumitem}
\usepackage{fancyhdr}
\usepackage{qrcode}
\usepackage{datetime2}
\usepackage{amsthm}
\usepackage{units}
\usepackage{xcolor}
\usepackage{xtab}
\usepackage{mdframed}

**Comment by dbmrq** [comment]
Oi, @dimicamp. Desculpe a demora, esses dias estão corridos. Vou tentar resolver esse warning assim que possível, mas não se preocupe, ele é inofensivo.

**Comment by crazytelli** [comment]
Olá, boa tarde. Este erro citado pelo usuário @dimicamp ainda persiste hoje (2019).
Package biblatex Warning: File 'brazilian-abnt-abnt.lbx' not found! Ignoring mapping 'brazilian-abnt' -> 'brazilian-abnt-abnt'.

O que isso significa exatamente? como resolver isso? Minhas versões da biblatex e biber estão atualizadas. Testei também no overleaf e mesma coisa.

@dbmrq

**Comment by dbmrq** [comment]
É só um aviso inofensivo, você pode ignorar. Ele está procurando o arquivo
dos termos em português com o nome errado e por isso não está encontrando,
mas isso não está afetando os resultados. Acho que ele reverte para o
arquivo correto automaticamente, só está avisando que não encontrou o
outro. Resolver isso no código deve ser simples, só não tive tempo de olhar
ainda. Mas não precisa se preocupar, o aviso não significa que tem algo
errado com o documento final.

**Comment by crazytelli** [comment]
@dbmrq dando continuidade ao tópico, eu identifiquei algo que talvez possa ajudá-lo com esse erro. O erro 

> Package biblatex Warning: File 'brazilian-abnt-abnt.lbx' not found! Ignoring mapping 'brazilian-abnt' -> 'brazilian-abnt-abnt'.
Só ocorre na versão 2019 do texlive pra mim.
Rodei o mesmo código no ubuntu, cuja versão do TeXLive é 2017 e o warning não se manifestou.
Rodando no Windows com TeXLive 2019 ocorre o warning.

**Comment by dbmrq** [comment]
Corrigi esse problema no branch `dev`.

**Comment by Punpuf** [comment]
Olá, bom dia. Este erro ainda está persistindo no meu projeto.

"Package biblatex Warning: File 'brazilian-abnt-abnt.lbx' not found! Ignoring mapping 'brazilian-abnt' -> 'brazilian-abnt-abnt'."

Estou usando o overleaf, com a configuração: 
\usepackage[brazil]{babel} 
\usepackage[style=abnt]{biblatex}

**Comment by fsbmat-ufv** [comment]
No overleaf, o problema persiste!

**Comment by caiogeraldes** [comment]
Uma solução um pouco bruta que funcionou aqui, pelo menos para os casos em que você está certo de que o `warning` não significa nada de importante é colocar no preâmbulo (acredito que antes de dar `\usepackage[style=abnt]{biblatex}` é:

```{latex}
\usepackage{silence}
\WarningsOff[biblatex]
```

**Comment by joaodefelipe** [comment]
Até onde testei, o PR ~#118~ #119 resolve este problema de forma definitiva. Se tudo correr certo, talvez a correção esteja incorporada no TeX Live 2024!

**Comment by dbmrq** [comment]
Valeu! As últimas versões, do branch dev, não foram enviadas para o CTAN, então não vão entrar no TeX Live, mas eu não me oponho caso alguém queira fazer o envio.
