### ISSUE TITLE
Desambiguação

### ISSUE THREAD

**Issue by kafran** [abntex/biblatex-abnt#36]
Prezados, estou com um pequeno problema de desambiguação. Já li o manual do biblatex mas não estou conseguindo sair do lugar. Tenho as seguintes entradas:

```
@Article{Pereira2016,
  author  = {given=Letícia Magalhães, family=Pereira},
  title   = {Mortalidade materna: como o descaso com a saúde 
da mulher impede a igualdade de gênero},
  journal = {Saúde \& Transformação Social / Health \& Social Change [en linea]},
  date    = {2016},
  volume  = {6},
  number  = {1},
  pages   = {70-78},
  issn    = {2178-7085},
  url     = {http://www.redalyc.org/articulo.oa?id=265345374007},
  urldate = {2018-07-23},
}

@MastersThesis{Pereira2014,
  author      = {Natalia Herculano Pereira},
  title       = {Modelo preditivo para intervenção coronária percutânea, 
em pacientes com infarto agudo do miocárdio, com supradesnivelamento do seguimento ST},
  institution = {Universidade Federal da Paraíba},
  date        = {2014},
  location    = {João Pessoa},
  pagetotal       = {94},
  type = {Dissertação (Mestrado)},
}
```
Pereira2016 e Pereira2014 geram as seguintes saídas nas referências:

PEREIRA, L. M. Mortalidade materna: como o descaso com a saúde da mulher impede a
igualdade de gênero. **Saúde & Transformação Social / Health & Social Change [en linea]**, v. 6, n. 1, p. 70–78, 2016. ISSN 2178-7085. Disponível em: <http://www.redalyc.org/articulo.oa?id=265345374007>. Acesso em: 23 jul. 2018.

PEREIRA, N. H. **Modelo preditivo para intervenção coronária percutânea, em pacientes com infarto agudo do miocárdio, com supradesnivelamento do seguimento ST**. 2014. 94 f. Dissertação (Mestrado) – Universidade Federal da Paraíba, João Pessoa.

Entretanto, no corpo do texto as saídas geradas são:

(L. M. PEREIRA, 2016) e (N. H. PEREIRA, 2014)

Entretanto, o efeito procurado é o exibido no tópico 6.1.2 da 10520:

(PEREIRA, L. M., 2016) e (PEREIRA, N. H., 2014)

Um outro problema de desambiguação é o da entrada abaixo, em que dois autores da mesma obra têm o mesmo sobrenome Cardoso de Souza:
```
@Article{Souza2015,
  author = {Cardoso de Souza, M. A. and Cardoso de Souza, T. H. S. and 
family=Gonçalves, given=A. K.,prefix=da S.},
  title   = {Fatores determinantes do near miss materno em
uma unidade de terapia intensiva obstétrica},
  journal = {Rev Bras Ginecol Obstet},
  date    = {2015},
  volume  = {37},
  number  = {11},
  pages   = {498--504},
  doi     = {10.1590/SO100-720320150005286},
  url     = {http://www.scielo.br/pdf/rbgo/v37n11/0100-7203-rbgo-37-11-00498.pdf},
  urldate = {2018-06-02},
}
```
Essa entrada gera a seguinte saída nas referências:

CARDOSO DE SOUZA, M. A.; CARDOSO DE SOUZA, T. H. S.; GONÇALVES, A. K. da S.
Fatores determinantes do near miss materno em uma unidade de terapia intensiva obstétrica.
**Rev Bras Ginecol Obstet**, v. 37, n. 11, p. 498–504, 2015. DOI: 10.1590/SO100-720320150005286. Disponível em: <http://www.scielo.br/pdf/rbgo/v37n11/0100-7203-rbgo-37-11-00498.pdf>. Acesso em: 2 jun. 2018.

Entretanto, a saída gerada no corpo do texto é

(M. A. CARDOSO DE SOUZA; T. H. S. CARDOSO DE SOUZA; GONÇALVES, 2015).

Mas o efeito esperado é:

(CARDOSO DE SOUZA, M. A.; CARDOSO DE SOUZA, T. H. S.; GONÇALVES, 2015)

A chamada de configuração do biblatex está assim:

```
\usepackage[
    backend=biber,
    style = abnt,
    language = brazil,
    giveninits,
    uniquename=init,
    extrayear,
    noslsn,
    backref
    ]{biblatex}
\addbibresource{mds.bib}
```

O documento tem sido produzido no Overleaf v.2, com a versão 3.1 do biblatex-abnt.

**Comment by dbmrq** [comment]
Oi, @kafran. Nos próximos dias vou conseguir olhar isso melhor pra confirmar se há um problema, mas com base nos testes eu acho que a desambiguação está funcionando corretamente.

Olha só: https://github.com/abntex/biblatex-abnt/blob/master/tests/NBR10520-2002_reference.pdf

Se você olhar a seção 7, vai encontrar o teste da desambiguação, com os exemplos "(BARBOSA, C., 1958)" e "(BARBOSA, O., 1959)".

Você pode olhar o código fonte pra ver como eu fiz pra imprimir essas entradas: https://github.com/abntex/biblatex-abnt/blob/master/bibtex/bib/biblatex-abnt/NBR10520-2002.bib

No teste só é impressa uma entrada de cada vez, né… não sei se pode haver algum problema especificamente quando mais de uma entrada é impressa. Também não sei que comandos de citação você está usando (`\cite` ou `\cites`?). Se realmente houver um problema, faça um exemplo mínimo incluindo tudo o que é necessário para reproduzir o problema, por favor. Use o pacote `filecontents` para incluir a bibliografia. Aqui estão algumas dicas: https://tex.meta.stackexchange.com/a/3225. Aí eu dou uma olhada assim que possível.

**Comment by kafran** [comment]
Ok @dbmrq, obrigado pela atenção. Vou dar uma olhada no exemplo teste. Mais tarde coloco um documento compartilhado no Overleaf com os exemplos completos.

**Comment by dbmrq** [comment]
@kafran Acabei de fazer um teste com o seguinte exemplo mínimo:

```tex
\documentclass{article}
\usepackage{filecontents}
\usepackage[style=abnt]{biblatex}

\begin{filecontents*}{\jobname.bib}
  @Article{Pereira2016,
    author = {given=Letícia Magalhães, family=Pereira},
    date   = {2014},
  }
  @MastersThesis{Pereira2014,
    author = {Natalia Herculano Pereira},
    date   = {2014},
  }
  @Article{Souza2015,
    author = {Cardoso de Souza, M. A. and Cardoso de Souza, T. H. S. and 
              family=Gonçalves, given=A. K.,prefix=da S.},
    date   = {2015},
  }
\end{filecontents*}

\addbibresource{\jobname.bib}

\begin{document}
  \noindent\cite{Pereira2016}\\
  \cite{Pereira2014}\\
  \cite{Souza2015}\\
  \cite{Pereira2014, Pereira2016}\\
  \cites{Pereira2014}{Pereira2016}
\end{document}
```

E o resultado parece estar correto:

<img width="870" alt="captura de tela 2018-08-18 as 01 52 04" src="https://user-images.githubusercontent.com/15813674/44295909-52e8ae00-a289-11e8-895b-dfbb19a53e8c.png">

Veja se você está usando a versão mais recente do biblatex-abnt.

**Comment by kafran** [comment]
Olá @dbmrq, desculpa não ter fornecido mais detalhes conforme prometido. Estou naquele corre...

Então, esses exemplos estão realmente funcionando. Entretanto, o problema ocorre quando temos:

1. O prefixo "de" está sendo abreviado para "d.";
2. Quando se utiliza o \textcite. A norma é silente em exemplificar casos para \textcite (quando os nomes dos autores estiverem incluídos na sentença) quando há esse tipo de ambiguidade, entretanto, se for seguir à risca o que traz o ponto 6.1.2 da 10520 ainda que não haja exemplo compatível, o resultado de \textcite para esse tipo de ambiguidade, no meu entender deveria ser:

Pereira, N. H de (2014) comenta que...

Eu não entendo nada de Tex ou Bib, então a muito sofrimento consegui chegar ao resultado pretendido com a gambiarra abaixo. Você com um olhar certamente mais apurado que o meu deverá entender as modificações que realizei.

https://gist.github.com/kafran/937547fac5008089e1f6bdc750ac92f0

Espero estar conseguindo me fazer entender, a falta de conhecimento no Tex ou Bib me traz certa dificuldade em me comunicar a respeito disso. Att.

**Comment by kafran** [comment]
Aproveito o comentário anterior e já pergunto, é possível utilizar a versão mais recente do biblatex-abnt com a versão do Biber/Biblatex do Texlive 2017 fazendo alguma pequena modificação?

Há outras correções na versão mais recente, como a citação do autor e multiplos anos que muito provavelmente terei que instalar o TexLive localmente para compilar o documento antes de entregar para a banca =( e eu não queria ter que fazer isso, realmente é muito confortável utilizar o [Overleaf](https://v2.overleaf.com?r=3038dad7&rm=d&rs=b).

Att.

**Comment by dbmrq** [comment]
Oi, @kafran.

Não entendi onde o problema número 1 ocorre, e ele não aparece nos seus exemplos. Se possível, adapte o exemplo mínimo que eu enviei para mostrar qual é o erro.

Quanto ao ponto número 2, eu discordo. Na minha opinião, quando usamos o `\textcite`, o nome do autor é parte do texto, e não da citação. Por isso, ele não aparece todo em maiúsculas, por exemplo. Consequentemente, acredito que o nome do autor deve ser formatado de modo a fazer sentido com o restante do texto, e não da mesma forma como aparece nas citações normais. Inclusive, mesmo nas citações entre parêntesis, o primeiro nome deve ser citado por extenso quando a inicial não é suficiente para a desambiguação. Então, se fossemos seguir o seu raciocínio, o texto ficaria, por exemplo, assim:

> Segundo Barbosa, Cássio (1965) e Barbosa, Celso (1965), blá blá blá […]

O que não me parece fazer o menor sentido, e eu nunca vi isso em nenhum artigo ou trabalho acadêmico.

Ademais, o próprio texto da norma me parece sugerir esse ponto de vista:

> 6.1.1 Quando o(s) nome(s) do(s) autor(es), instituição(ões) responsável(eis) estiver(em) incluído(s) na sentença, indica-se a data, entre parênteses, acrescida da(s) página(s), se a citação for direta.
> 
> Exemplos:
> - Em Teatro Aberto (1963) relata-se a emergência do teatro do absurdo.
> - Segundo Morais (1955, p. 32) assinala "[…] a presença de concreções de bauxita no Rio Cricon."

E isso é, de fato, o que ocorre com o uso do comando `\textcite`: o nome do autor é incluído na sentença, então apenas a data é indicada entre parêntesis.

Voltando ao meu exemplo anterior, o normal seria dizer:

> Segundo Cássio Barbosa e Celso Barbosa, blá blá blá […]

Nesse caso, o nome dos autores está incluído na sentença, então indicamos a data entre parêntesis, seguindo à risca o item 6.1.1 da norma:

> Segundo Cássio Barbosa (1965) e Celso Barbosa (1965), blá blá blá […]

Por fim, acho que todos concordam, no mínimo, que o manual é extremamente impreciso e mal escrito. Ele dá margem às duas possibilidades, de modo que nenhuma delas pode ser considerada inadequada. Portanto, o comportamento atual está correto, além de, na minha opinião, ser muito mais razoável e elegante.

Tendo isso em vista, por ora me parece ser melhor manter o comportamento atual. Se houver mais demanda pela outra possibilidade, posso pensar em acrescentá-la ao estilo como uma opção adicional, mas no momento isso me parece desnecessário, ainda mais considerando que você já conseguiu o efeito desejado por conta própria. :)

**Comment by dbmrq** [comment]
Ah, e sobre usar a versão mais recente do estilo com versões anteriores do BibLaTeX/biber, infelizmente isso não é possível. Mas imagino que você possa enviar as versões mais novas desses pacotes para o Overleaf junto com seu documento… só não sei se é possível fazer ele usar um binário específico do biber, mas você pode dar uma olhada.

De qualquer forma, eu recomendaria que você compile o documento localmente mesmo; essas plataformas online nunca são tão completas e flexíveis. Se você não quiser, nem precisa instalar a versão completa do TeX Live. Este é o script que eu escrevi para instalar o TeX Live no Travis para testar as novas versões do biblatex-abnt: https://github.com/abntex/biblatex-abnt/blob/master/tests/texlive.sh

Se você olhar o histórico, as compilações completas demoram em média 2-3 minutos: https://travis-ci.org/abntex/biblatex-abnt/builds

E nem metade desse tempo é gasta na instalação de fato. Então você consegue instalar uma versão do TeX com o mínimo pra usar o biblatex-abnt em mais ou menos um minuto. Só vai precisar instalar também os outros pacotes que você usa, claro.

**Comment by kafran** [comment]
```latex
\documentclass{article}

\usepackage[brazil]{babel}
\usepackage{csquotes}
\usepackage[T1]{fontenc}		% Selecao de codigos de fonte.
\usepackage{times}
\usepackage[utf8]{inputenc}		% Codificacao do documento (acentos)

\usepackage[
    backend=biber,
    style = abnt,
    giveninits=true,
    uniquename=mininit,
%    uniquelist=false,
    extrayear,
    %noslsn,
    backref
    ]{biblatex}

\usepackage{filecontents}

\begin{filecontents*}{bib.bib}

@Article{Medeiros2014,
  author  = {family=Medeiros, given=Amira Rose Costa and family=Araújo, given=Yana Balduíno, prefix=de and family=Vianna, given=R. P. de T. and family=Moraes, given=Ronei Marcos, prefix=de},
  title   = {Modelo de suporte à decisão aplicado à identificação de indivíduos não aderentes ao tratamento anti-hipertensivo},
  journal = {SAÚDE DEBATE},
  date    = {2014},
  volume  = {38},
  number  = {100},
  pages   = {104-118},
  doi     = {10.5935/0103-104.20140016},
  urldate = {2018-08-05},
  address = {Rio de Janeiro},
}

@Article{Medeiros2016,
  author        = {family=Medeiros, given=Ana Lúcia, prefix=de and family=Santos, given=Sérgio Ribeiro, prefix=dos and family=Cabral, given=R. W. de L. and family=Silva, given=Juliana Paiva Góes and family=Nascimento, given=N. de M.},
  title         = {Assessing nursing diagnoses and interventions in labour and high-risk pregnancies},
  journal       = {Revista Gaúcha de Enfermagem},
  date          = {2016},
  volume        = {37},
  number        = {3},
  issn          = {1983-1447},
  doi           = {10.1590/1983-1447.2016.03.55316},
  urldate       = {2018-06-02},
}

@Article{Medeiros2016a,
  author    = {family=Medeiros, given=Leidyanny Barbosa, prefix=de and family=Trigueiro, given=Débora Raquel Soares Guedes and family=Silva, given=Daiane Medeiros, prefix=da and family=Nascimento, given=João Agnaldo, prefix=do and family=Monroe, given=Aline Aparecida and family=Nogueira, given=J. de A. and family=Leadebal, given=Oriana Deyze Correia Paiva},
  title     = {Integração entre serviços de saúde no cuidado às pessoas vivendo com {AIDS}},
  journal   = {Ciência {\&} Saúde Coletiva},
  date      = {2016-02},
  subtitle  = {uma abordagem utilizando árvore de decisão},
  volume    = {21},
  number    = {2},
  pages     = {543--552},
  doi       = {10.1590/1413-81232015212.06102015},
  urldate   = {2018-06-13},
  publisher = {{FapUNIFESP} ({SciELO})},
}
\end{filecontents*}

\addbibresource{bib.bib}

\begin{document}
\textcite{Medeiros2014} disse que \dots

\textcite{Medeiros2016a} disse que \dots

\textcite{Medeiros2016} isso \dots

\cites{Medeiros2014}{Medeiros2016}{Medeiros2016a}

\renewcommand{\bibname}{Referências} 
\renewcommand*{\bibfont}{\raggedright}
\printbibliography

\end{document}
```
![screenshot_2018-09-02_10-27-34](https://user-images.githubusercontent.com/1889828/44956447-e41b6f80-ae9a-11e8-897f-55cd97ea6ed0.png)

Concordo contigo. O problema é que no OverLeaf o TexLive é ainda o 2017. Instalei o TexLive 2018 na minha máquina seguindo a tua dica e resolveu os problemas. Só há um erro ainda, no Prefixo "de" na citação entre parenteses.

**Comment by dbmrq** [comment]
Esquisito, não sei por que esse é o comportamento padrão do BibLaTeX. Mas já arrumei no estilo, acho que agora está tudo certo. (Você vai ter que instalar o último commit manualmente.)

**Comment by kafran** [comment]
Ok, estou trabalhando no OverLeaf mas para entregar compilo localmente. Daqui para o final do ano o OverLeaf atualiza para o TexLive 2018 aí fica mais fácil enviar a versão mais atualizada pra lá.

**Comment by dbmrq** [comment]
Esqueci de responder isso, desculpe. A opção `useprefix` faz com que o prefixo seja usado na citação. Com essa opção, uma seria citada como “(DE SOUZA, 2018)” em vez de só “(SOUZA, 2018)”, por exemplo. Mas ela não interfere na abreviação, então o comportamento padrão do BibLaTeX ao usar abreviações ainda seria imprimir “D. SOUZA”. Não sei se isso é um erro ou se tem idiomas com prefixos mais longos que costumam ser abreviados. 🤷🏻‍♂️ 

Mas de qualquer forma o biblatex-abnt deve estar lidando com isso direito na última versão, com ou sem a opção `useprefix`.

**Comment by kafran** [comment]
Show. @dbmrq que trabalho incrível tens feito. Parabéns. Gostaria de um dia te pagar um café. Att.

**Comment by dbmrq** [comment]
Hahaha, qué isso. Que bom que está sendo útil. :)
