### ISSUE TITLE
Citação indireta constando a inicial do primeiro nome

### ISSUE THREAD

**Issue by la-costa** [abntex/biblatex-abnt#37]
Estou utilizando a versão 3.2 e em algumas citações indiretas (não são todas) estão sendo geradas com a inicial do primeiro nome de um autor.

Citação obtida:  (BOISOT, M.; NORDBERG, 2011) :heavy_multiplication_x:
Citação esperada: (BOISOT; NORDBERG, 2011) :heavy_check_mark:

```latex
@inbook{boisot:2011,
	author       = {Boisot, Max and Nordberg, Markus},
	title        = {A Conceptual Framework},
	subtitle     = {The I-Space},
	booktitle    = {Collisions and Collaboration: The Organization of Learning in the ATLAS Experiment at the LHC},
	chapter      = {3},
	pages        = {28-54},
	publisher    = {Oxford University Press},
	year         = {2011},
	address      = {Oxford, Reino Unido},
	month        = 7,
	doi	       = {10.1093/acprof:oso/9780199567928.003.0003}
}
```

Com o author como {Max Boisot and Markus Nordberg} acontece o mesmo comportamento.

**Comment by kafran** [comment]
@la-costa Só existe essa obra de Boisot ou tem outras?

**Comment by la-costa** [comment]
Oi @kafran 

Tem outros, mas não me parecem ambíguos nas referências. 

Esse problema acontece com outros autores, são casos pontuais. Infelizmente, eu não consegui achar o motivo do comportamento. 

A citação direta é realizada corretamente, apenas na indireta aparece o problema e sempre é no primeiro autor.

Por exemplo, tem esse abaixo, que somente tem esta obra declarada no arquivo *.bib.

Citação obtida: (ANDERSON, T.; CURTIS; WITTIG, 2015) :heavy_multiplication_x:
Citação esperada: (ANDERSON; CURTIS; WITTIG, 2015) :heavy_check_mark:

```latex
@article{anderson:2015,
	author = {Anderson, Tara and Curtis, Andrew and Wittig, Claudia},
	title = {Definition and Theory in Social Innovation},
	subtitle = {The theory of social innovation and international approaches},
	year = {2015},
	number = {33},
	month = 1,
	url = {https://www.zsi.at/en/object/publication/3641},
	address = {Viena, Austria},
	isbn = {1818-4162},
	journal = {ZSI Discussion Paper}
}
```

**Comment by dbmrq** [comment]
Oi @la-costa.

Você disse que o problema acontece mesmo quando a entrada `anderson:2015` é a única usada. Eu acabei de fazer um teste com o seguinte exemplo mínimo e funcionou direitinho:

```tex
\documentclass{article}
\usepackage[style=abnt]{biblatex}

\usepackage{filecontents}

\begin{filecontents*}{\jobname.bib}
@article{anderson:2015,
	author = {Anderson, Tara and Curtis, Andrew and Wittig, Claudia},
	title = {Definition and Theory in Social Innovation},
	year = {2015},
}
\end{filecontents*}

\addbibresource{\jobname.bib}

\begin{document}
  \cite{anderson:2015}
\end{document}
```

<img width="693" alt="captura de tela 2018-08-20 as 01 09 34" src="https://user-images.githubusercontent.com/15813674/44319993-b9023c00-a415-11e8-8720-f290190a1ed5.png">

Tente chamar o BibLaTeX com as opções `uniquename=false` e `uniquelist=false`. Isso vai desativar a desambiguação. Se o seu problema não ocorrer mais, é porque o BibLaTeX estava considerando essa entrada ambígua, como o @kafran sugeriu. Ele faz um bom trabalho em identificar quais entradas precisam ser desambiguadas, mas não é perfeito (a issue https://github.com/abntex/biblatex-abnt/issues/23 apresenta outro exemplo problemático). Se você achar que o BibLaTeX está errado e quiser desativar a desambiguação só para uma entrada específica, isso também é possível usando o campo `options`. Consulte o manual do BibLaTeX para mais detalhes.

Como não parece haver um problema com o biblatex-abnt, vou fechar essa issue, mas fique à vontade para me corrigir se tiver mesmo algo errado. Nesse caso, envie um exemplo mínimo que mostre o problema, como o que eu usei acima, por favor.

**Comment by la-costa** [comment]
Olá @dbmrq e @kafran 

Fiz o teste com `uniquename=false` e `uniquelist=false` e resolveu.

Acho que entendi o que é a desambiguação... Eu tenho duas entradas com o mesmo sobrenome de autor, porém com nomes, obras e anos distintos. Para mim não seria algo ambíguo, mas o biblatex-abnt entendeu que seria.

Segue abaixo o exemplo das entradas que geram o comportamento.

```latex
\documentclass{article}
\usepackage[backend=biber,style=abnt]{biblatex}

\usepackage{filecontents}

\begin{filecontents*}{\jobname.bib}
@article{anderson:2015,
        author = {Anderson, Tara and Curtis, Andrew and Wittig, Claudia},
        title = {Definition and Theory in Social Innovation},
        subtitle = {The theory of social innovation and international approaches},
        year = {2015},
        number = {33},
        month = 1,
        url = {https://www.zsi.at/en/object/publication/3641},
        address = {Viena, Austria},
        isbn = {1818-4162},
        journal = {ZSI Discussion Paper}
}
@book{anderson:1983,
        author = {Anderson, John R.},
        title = {The  Architecture of Cognition},
        year = {1983},
        isbn = {0674044258},
        publisher = {Harvard University Press},
        address = {Cambridge, MA, USA},
}
\end{filecontents*}

\addbibresource{\jobname.bib}

\begin{document}
  \cite{anderson:2015}
  \cite{anderson:1983}
\end{document}
```
![screenshot from 2018-08-20 08-45-14](https://user-images.githubusercontent.com/16106846/44338785-73fdfa00-a455-11e8-8fdd-7774be3d8dc0.png)

**Comment by la-costa** [comment]
Como sugestão, talvez fosse interessante incluir na documentação do biblatex-abnt uma seção de FAQ.

**Comment by dbmrq** [comment]
> Eu tenho duas entradas com o mesmo sobrenome de autor, porém com **nomes, obras e anos distintos**. Para mim não seria algo ambíguo, mas o biblatex-abnt entendeu que seria.

- A obra ser diferente é irrelevante, já que o título não aparece na citação.

- No seu exemplo, os anos são diferentes, mas a ABNT parece exigir a desambiguação mesmo assim, como vemos no item 6.1.2 da NBR 10520:

    <img width="466" alt="captura de tela 2018-08-20 as 21 10 17" src="https://user-images.githubusercontent.com/15813674/44373692-dfc97c80-a4c0-11e8-8866-24600e1fa348.png">

- No seu exemplo, o primeiro nome é ambíguo, mas a lista de nomes tomada como um todo não é. O comportamento padrão do BibLaTeX, nesse caso, é o de acrescentar as iniciais só ao primeiro nome. A ABNT não diz nada sobre isso, então acho que podemos fazer o que bem entendermos. Considerando o ponto anterior, me parece que o mais coerente seria sermos conservadores e, na dúvida, acrescentarmos as iniciais. Mas eu concordo que, nesse caso, a desambiguação é desnecessária… e, mais importante, a citação fica muito feia com as iniciais em só um dos nomes da lista,  rs. Considerando isso, mudei o comportamento padrão para não desambiguar as citações nesse caso. Usando o commit https://github.com/abntex/biblatex-abnt/commit/7a86c71e1206969744f5bd05de6f3236e05e3b95, as iniciais não são mais acrescentadas no seu exemplo. :)

Caso alguém queira voltar ao comportamento anterior, é só chamar o BibLaTeX com a opção `uniquename=full`.

---

Quanto a incluir um FAQ na documentação, é uma ótima ideia, mas agora eu não vou ter tempo de fazer isso… também tenho uma tese para entregar até o fim do ano, rs. Caso alguém queira colaborar com uma PR, será muito bem vinda.

**Comment by la-costa** [comment]
Blz! Com a explicação já fica registrado no issue e mais para a frente é só juntar num FAQ. 
Por hora não consigo auxiliar nisso... :-(

**Comment by kafran** [comment]
Eu acho um FAQ desnecessário. O manual serve para isso, é vivo e deve ser atualizado. Ou atualiza-se o manual já disponibilizado ou transfere o manual para o Wiki aqui do Github, não sei. Mas um FAQ vai ser apenas mais um local para alguém manter. Sem manutenção, não importa se é FAQ, se é manual, se é wiki, a informação não terá utilidade. Posso tentar ajudar depois atualizando o manual, inserindo as novas opções disponíveis, etc. Talvez inserir no manual uma seção tratando das desambiguações.

**Comment by kafran** [comment]
Ah sim. Agora entendi. Concordo. Facilitaria principalmente a vida daqueles que não têm muita familiaridade com a língua inglesa, já que o manual do próprio BibLaTeX é bem chatinho de ler.

**Comment by kafran** [comment]
```latex
\documentclass{article}

\usepackage[
    backend=biber,
    style = abnt,
    giveninits=true,
    uniquename=mininit,
%    uniquelist=false,
    extrayear,
    %noslsn,
    backref
    ]{biblatex}

\usepackage{filecontents}

\begin{filecontents*}{\bib.bib}
@Article{Medeiros2014,
  author  = {family=Medeiros, given=Amira Rose Costa and family=Araújo, given=Yana Balduíno, prefix=de and family=Vianna, given=R. P. de T. and family=Moraes, given=Ronei Marcos, prefix=de},
  title   = {Modelo de suporte à decisão aplicado à identificação de indivíduos não aderentes ao tratamento anti-hipertensivo},
  journal = {SAÚDE DEBATE},
  date    = {2014},
  volume  = {38},
  number  = {100},
  pages   = {104-118},
  doi     = {10.5935/0103-104.20140016},
  urldate = {2018-08-05},
  address = {Rio de Janeiro},
}

@Article{Medeiros2016,
  author        = {family=Medeiros, given=Ana Lúcia, prefix=de and family=Santos, given=Sérgio Ribeiro, prefix=dos and family=Cabral, given=R. W. de L. and family=Silva, given=Juliana Paiva Góes and family=Nascimento, given=N. de M.},
  title         = {Assessing nursing diagnoses and interventions in labour and high-risk pregnancies},
  journal       = {Revista Gaúcha de Enfermagem},
  date          = {2016},
  volume        = {37},
  number        = {3},
  issn          = {1983-1447},
  doi           = {10.1590/1983-1447.2016.03.55316},
  urldate       = {2018-06-02},
}

@Article{Medeiros2016a,
  author    = {family=Medeiros, given=Leidyanny Barbosa, prefix=de and family=Trigueiro, given=Débora Raquel Soares Guedes and family=Silva, given=Daiane Medeiros, prefix=da and family=Nascimento, given=João Agnaldo, prefix=do and family=Monroe, given=Aline Aparecida and family=Nogueira, given=J. de A. and family=Leadebal, given=Oriana Deyze Correia Paiva},
  title     = {Integração entre serviços de saúde no cuidado às pessoas vivendo com {AIDS}},
  journal   = {Ciência {\&} Saúde Coletiva},
  date      = {2016-02},
  subtitle  = {uma abordagem utilizando árvore de decisão},
  volume    = {21},
  number    = {2},
  pages     = {543--552},
  doi       = {10.1590/1413-81232015212.06102015},
  urldate   = {2018-06-13},
  publisher = {{FapUNIFESP} ({SciELO})},
}\end{filecontents*}

\addbibresource{\bib.bib}

\begin{document}
\textcite{Medeiros2014} disse que \dots

Já \textcite{Medeiros2016a} disse que \dots

e \textcite{Medeiros2016} isso \dots

\renewcommand{\bibname}{Referências} 
\renewcommand*{\bibfont}{\raggedright}
\printbibliography

\end{document}
```
