### ISSUE TITLE
Citar nome do autor com primeiras letras maiúsculas

### ISSUE THREAD

**Issue by douglasrizzo** [abntex/biblatex-abnt#38]
Olá. Eu busco uma forma de citar uma obra pelo nome do autor, como faz o comando `\citeauthoronline{obra}` do abntex2cite. Pelo que vi no manual do biblatex-abnt, não existe forma de fazer isso.

No limite eu gostaria de realizar citações como "Turing, 1950", as quais eu fazia originalmente através de `\citeauthoronline{obra}, \citeyear{obra}`.

Tentei fazer `\citeauthor*{obra}, \citeyear*{obra}` mas consegui "TURING, A., 1950".

**Comment by dbmrq** [comment]
Essa é uma exigência bem esquisita e não tem nada a ver com o estilo da ABNT, mas estou de bom humor e o comando `\textcite*` não fazia nada mesmo, então aí vai. Com o último commit, `\textcite*{obra}` faz o que você quer (e.g., "Turing, 1950"). 🍻

**Comment by douglasrizzo** [comment]
Hahahaha, obrigado. Se tivesse algum comando do _biblatex_ ou algum _hack_ que eu tentei que tivesse funcionado, eu não teria pedido. Minha instituição pede que nós referenciemos _floats_ da seguinte forma:

> Tabela 1: tabela importante
> ...
> Fonte: Autor "adaptado de" Turing, 1950

Eu, que sou o mantenedor da classe de formatação da instituição, havia criado o comando `\citefloat{obra}` que fazia isso, mas ele depende de comandos que disponibilizam o nome do autor e o ano.

Eu tentei usar pacotes que disponibilizam comandos como `\sentencecase{\citeauthor*{obra}}` ou `{\MakeSentenceCase \citeauthor*{obra}}`, mas não rolou...

**Comment by douglasrizzo** [comment]
Tem um problema, o `\textcite*{obra}` adiciona parênteses no ano, então não gera "_Turing, 1950_", mas sim "_Turing (1950)_".

**Comment by dbmrq** [comment]
Isso com o último commit? Não deveria. Se estiver com o último commit mesmo
manda um exemplo mínimo que eu olho assim que puder.

Em qui, 11 de out de 2018 às 15:42, Douglas De Rizzo Meneghetti <
notifications@github.com> escreveu:

**Comment by dbmrq** [comment]
Ah, que bom! :)
Disponha.
