### ISSUE TITLE
biblatex to drop xstring

### ISSUE THREAD

**Issue by moewew** [abntex/biblatex-abnt#39]
Apologies for writing in English, Portuguese is not my forte.

We are currently planning on getting rid of `xstring` code in `biblatex`. As a consequence `biblatex` would not require `xstring` any more and would not load the `xstring` package itself any more. `biblatex` styles that need `xstring` would have to load the package explicitly themselves. See https://github.com/plk/biblatex/pull/816 for the current state of affairs.

Your style uses some `xstring` commands, for example

https://github.com/abntex/biblatex-abnt/blob/97ff3adb204b9cd82de99e26c6d99520c51b5c7f/latex/bbx/abnt.bbx#L435-L437

so to continue working properly, `abnt.bbx` should load `xstring`.

Even if it turns out that the change can not go through as planned, it is still a very good idea to load `xstring` explicitly if your style needs it.

We are hoping to release a new version of `biblatex` in the not too distant future (I can't promise any ETA as of now, there will be a pre-release announcement on [comp.text.tex](https://groups.google.com/forum/#!forum/comp.text.tex)). You can learn more about the upcoming changes in https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.md. If you can find time to test your style against the new dev version (https://sourceforge.net/projects/biblatex/files/development/, you'll also need Biber 2.12 from https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/binaries/) feedback would be appreciated.

**Comment by dbmrq** [comment]
No problem. Thank you for letting me know! I'll make the change and try to test the new version as soon as possible. Cheers! 🍺

**Comment by dbmrq** [comment]
Awesome, thank you! I’m on a trip, so I was waitinng until I got back home to look into it. I’ll try moving to `expl3` then, I’ll leave this issue open to remind me. (If you get bored and feel like helping, with that or anything else, I’ll be very grateful. I have pretty much no idea what I’m doing here, as you can see from my code, which is a huge mess, haha.)

**Comment by moewew** [comment]
`biblatex` 3.12 was released a while ago, so currently all users of `biblatex-abnt` must load `xstring` manually. So far this does not seem to have caused much of a stir, but I was reminded of this issue when I was looking into https://tex.stackexchange.com/q/460412/35864 just a few moments ago.

It would be great if the code on GitHub could make its way to CTAN soon, so people are not forced to change their documents. Let me know if I can be of any assistance.

**Comment by dbmrq** [comment]
Oh, I'm sorry about this. I was on a long trip and I still didn't manage to deal with everything I need to since I got back. I just sent the latest version to CTAN. Thanks again for all your help!

**Comment by moewew** [comment]
Thank you very much.
