### ISSUE TITLE
URLs com "¡" e "¿" nas referências

### ISSUE THREAD

**Issue by gabrielbvargas** [abntex/biblatex-abnt#45]
Ao adicionar uma referência .bib que utilizar como parâmetro um dado "url = ...", essa url ao aparecer nas referências, ao invés de ser mostrada como:
<https://link.com/>
é mostrada como:
¡https://link.com/¿
Imagino que o problema seja no verbatim. Estou usando o editor TexLive no Ubuntu 18.04, compilando as referências com o biber. Também tentei compilar o código no Overleaf, mas o mesmo problema ocorreu.

**Comment by dbmrq** [comment]
Envie um exemplo mínimo, por favor: https://tex.meta.stackexchange.com/a/3301

**Comment by igorkf** [comment]
Olá, isso também está acontecendo comigo.
Veja minha referência:
```
@book{James2021,
  author = {James, Gareth and Witten, Daniela and Hastie, Trevor and Tibshirani, Robert},
  biburl = {https://www.bibsonomy.org/bibtex/2444186c86d18bddb4433c12fa126f6be/lopusz_kdd},
  publisher = {Springer},
  title = {An Introduction to Statistical Learning: with Applications in R},
  url = {https://faculty.marshall.usc.edu/gareth-james/ISL/},
  year = {2021}
}
```

Como está aparecendo:
> JAMES, Gareth et al. An Introduction to Statistical Learning: with Applications in R. Springer, 2021. Disponível em:¡https://faculty.marshall.usc.edu/gareth-james/ISL/¿.

**Comment by ghost** [comment]
Olá, Gabriel e Igor.

Por hora resolvi o problema modificando o campo do url.

 \DeclareFieldFormat{url}{\bibstring{urlfrom}\addcolon\addspace\normalfont\url{#1}}

**Comment by Gustvo** [comment]
Vou reviver esse tópico porquê é um problema que tive antes e continuo tendo - tenho que colocar no preâmbulo de cada documento o código acima para renderizar urls corretamente.

**Comment by A-Infor** [comment]
Estou tendo o mesmo problema em 2025!
