### ISSUE TITLE
macro 'cite:noname' undefined.

### ISSUE THREAD

**Issue by xR2** [abntex/biblatex-abnt#5]
Boa tarde, 

primeiramente preciso agradeçer a todos que tomam iniciativas de facilitar a nossa jornada "contra" a ABNT no LaTeX.

Provavelmente eu fiz alguma besteira tentando atualizar manualmente.
Eu utilizava um arquivo _abnt-numeric gambiarra_ ([abnt-numeric.bbx.txt](https://github.com/abntex/biblatex-abnt/files/333702/abnt-numeric.bbx.txt)) que não funciona mais no biblatex 3.3, agora estou testando o biblatex-abnt e tenho esse erro.

`Package biblatex Error: Bibliography macro 'cite:noname' undefined.`
Embora no arquivo cbx o macro esteja definido. Seria um erro da  minha bibliografia (.bib) ?

Fiz tudo conforme o manual, instalação, etc.
`\usepackage[backend=biber,style=abnt,language=brazilian,alldates=long,sorting=none,scbib,hyperref]{biblatex}`

e para citar o `\cite{bibkey}`.
BTW, eu preciso das referencias no sistema numérico estranhamente não fala nada sobre isso no manual.

**Comment by danielbmarques** [comment]
Uhm, eu pediria um exemplo mínimo, mas como você já disse que o erro foi seu, acho que não devo conseguir reproduzi-lo, né.

Para garantir que o problema não é no seu arquivo, tente compiladar o abnt-biblatex.tex, que está aqui no repositório, e veja se dá algum erro.

Caso positivo, vou precisar de mais informações. O que foi essaalguma besteira que você fez?

Sobre o sistema número, ainda não tem como usá-lo, infelizmente. Eu comecei fazendo o biblatex-abnt pra eu mesmo usar, e nunca uso o sistema numérico, então não o implementei. Vou ver de fazer isso quando eu tiver um tempo.

**Comment by ycherem** [comment]
Daniel

O sistema numérico funciona normalmente. Já fiz alguns testes.
Em 26/06/2016 14:39, "Daniel Marques" <notifications@github.com> escreveu:

**Comment by xR2** [comment]
O abnt-testcase.tex compila sem problemas, mas quando tento citar uma referencia minha, bang da o mesmo erro. 
Abri o meu .bib percebi que algumas referencias não tem autor... aí tentei citar apenas uma com autor e... nada de erro! Então aparentemente o problema é citar uma entrada que não tem autor.

A besteira foi ter colocado os arquivos do bibilatex-abnt direto nos diretorios `\tex\latex\biblatex\bbx\` `cbx` e `lbx`.

O meu arquivo gambiarra funcionava muito bem antes de atualizar o bibilatex pra 3.3, talvez de pra converter eu tentei mas não entendi muito bem como funciona os comandos novos. Se eu puder ajudar em alguma coisa é só dizer.

E aqui vai o MWE:

```
\documentclass[a4paper]{article}
\usepackage[brazil]{babel}
\usepackage{lmodern}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{filecontents}
\usepackage{hyperref}
\usepackage[backend=biber,style=abnt,language=brazilian,alldates=long,sorting=none,scbib,hyperref]{biblatex}
\usepackage[brazil]{babel}
\usepackage[autostyle]{csquotes}

\addbibresource{shortbib.bib}

\begin{filecontents}{shortbib.bib}
@Book{IAEA_est_2050,
  publisher = {International Atomic Energy Agency},
  title     = {Energy, Electricity and Nuclear Power Estimates for the Period up to 2050},
  year      = {2015},
  series    = {Reference Data Series 1},
  edition   = {2015},
  note      = {RDS - 1/35},
  isbn      = {978-92-0-105915-4},
  groups    = {IAEA},
  url       = {http://www-pub.iaea.org/books/IAEABooks/7857/Estimation-of-Global-Inventories-of-Radioactive-Waste-and-Other-Radioactive-Materials},
  urldate   = {2015-10-15},
}
@thesis{eliseu84,
    title       = {Verbos ergativos do Português},
    subtitle    = {descrição e análise},
    author      = {André Manuel Godinho Simões Eliseu},
    type        = {Dissertação (Mestrado em Linguística)},
    institution = {Universidade de Lisboa},
    location    = {Lisboa},
    eventyear   = {1985},
}
\end{filecontents}
\begin{document}

	\cite{eliseu84}
	
	\cite{IAEA_est_2050}
	\printbibliography
\end{document}
```

**Comment by danielbmarques** [comment]
@ycherem 
Ah, que ótimo! Eu nem tinha olhado pra isso. Pensei que teria que acrescentar algo aos drivers da bibliografia pros números aparecerem corretamente. Você fez o que, só usou `bibstyle=abnt, citestyle=numeric`?

**Comment by danielbmarques** [comment]
@xR2 
Tem razão, já entendi qual é o problema. Vou tentar arrumar ainda hoje, mais tarde posto aqui o resultado.

**Comment by ycherem** [comment]
Daniel,

Tem razão, erro meu, desculpe -- fiz isso mesmo, sai corretamente no texto
e nem percebi que no fim não aparecem os números de chamada -- mas o resto
a formatação é a mesma. Acho que só falta colocar os números na frente das
entradas, e escolher a ordem bibliográfica como ordem de chamada no texto.

Youssef Cherem
________________
!المسيح قام! حقاً قام

**Comment by danielbmarques** [comment]
Vamos lá, enviei algumas mudanças para o branch `develop-2.0`.
Prestem atenção que os arquivos que estão lá exigem biblatex v3.4 e biber v2.5, ou seja, vocês precisariam do TeXLive 2016.

Acho que agora as citações sem autor estão funcionando direitinho. O exemplo do @xR2 fica assim:

![captura de tela 2016-06-26 as 17 55 32](https://cloud.githubusercontent.com/assets/15813674/16364869/410017d0-3bc7-11e6-82c5-71826494a942.png)

Além disso, acrescentei o estilo `abnt-numeric`.

Por enquanto o que ele faz é simplesmente acrescentar os números do estilo `numeric` ao estilo `abnt`. Só que eles ficam entre colchetes… e pelo que eu vi têm que ficar sem colchetes na bibliografia e sobrescritos nas citações. Depois vou tentar arrumar isso.

Não sei se vocês já estão usando o TeXLive 2016, mas se puderem testar tudo isso seria bom. Como eu não uso o estilo numérico, não vou perceber se houverem erros.

**Comment by xR2** [comment]
Aqui compilou normal Daniel, com o mesmo resultado.

Da nbr 10520:

> 6.2 Sistema numérico
Neste sistema, a indicação da fonte é feita por uma numeração única e consecutiva, em algarismos arábicos, remetendo à lista de referências ao final do trabalho, do capítulo ou da parte, na mesma ordem em que aparecem no texto. Não se inicia a numeração das citações a cada página.
6.2.1 O sistema numérico não deve ser utilizado quando há notas de rodapé.
6.2.2 A indicação da numeração pode ser feita entre parênteses, alinhada ao texto, ou situada pouco acima da linha do texto em expoente à linha do mesmo, após a pontuação que fecha a citação.
Exemplos: Diz Rui Barbosa: "Tudo é viver, previvendo.” (15)
Diz Rui Barbosa: "Tudo é viver, previvendo."15

**Comment by danielbmarques** [comment]
PS: @xR2, algumas dicas: como você está usando versalete na bibliografia, pode usar `\mkbibacro{RDS}` ali onde diz "RDS". Assim o `biblatex` vai entender que isso é um acrônimo e usar versalete ou não dependendo da opção que você escolher. Além disso, acho que fica muito melhor usando números *old style*, especialmente junto com o versalete (é só usar o pacote `cfr-lm` em vez de `lmodern`). E a ABNT não fala de casos como esse em que a edição é um ano, mas acho que ficaria melhor usar `edition = {Ed. 2015}`.
Fazendo tudo isso o resultado fica assim:

![captura de tela 2016-06-26 as 18 55 52](https://cloud.githubusercontent.com/assets/15813674/16365196/a093937c-3bcf-11e6-8abc-81424e4f8ff1.png)

**Comment by danielbmarques** [comment]
@xR2 
Como assim "o mesmo resultado"? Isso é um resultado positivo? Rs.

**Comment by danielbmarques** [comment]
Enviei mais uma atualização pro `develop-2.0`.

```tex
Blabla \cite{IAEA_est_2050}
    
Blabla \supercite{IAEA_est_2050}
```

Agora imprime:

![captura de tela 2016-06-26 as 19 09 24](https://cloud.githubusercontent.com/assets/15813674/16365270/85b5b088-3bd1-11e6-9498-cbaed08ed249.png)

Então acho que agora está tudo de acordo com a ABNT. 😎
([A norma de 2002](http://www.usjt.br/arq.urb/arquivos/abntnbr6023.pdf) diz que a chamada pode ser tanto entre parêntesis quanto sobrescrita.)

**Comment by xR2** [comment]
@danielbmarques Mesmo resultado = o print que você postou. Sim estou com TeXLive 2016.
Quanto as sugestões, ainda estou digerindo hehehe, mas a principio vou adotar sim, muito obrigado.

**Comment by danielbmarques** [comment]
Legal! Vou deixar essa issue aberta mais um pouco, se você achar algo de estranho me avisa. Se estiver tudo certo mesmo, daqui uns dias eu envio pro ctan e a atualização já entra no TeXLive.

**Comment by xR2** [comment]
Agora já não consigo reproduzir, mesmo depois de baixar os arquivos novos. 

Se uso `style=abnt-numeric` da erro:

> Package biblatex Error: Style 'abnt-numeric' not found. \RequireCitationStyle{\blx@cbxfile}

E se utilizo `style=abnt,citestyle=numeric` não aparecem os números nas referências. 

Aproposito, eu não tenho diretório `biblatex-contrib`, aqui estou usando assim `C:\texlive\2014\texmf-dist\tex\latex\biblatex\biblatex-abnt`. Sim 2014 mas a versão é 2016, resolvi manter o nome original sabe-se lá pq.

**Comment by danielbmarques** [comment]
@xR2 
Mas você copiou também os arquivos `abnt-numeric.bbx` e `abnt-numeric.cbx`?

**Comment by danielbmarques** [comment]
E se você tem o TeXLive 2016, você tem o diretório `C:\texlive\2014\texmf-dist\tex\latex\biblatex-abnt`. Pode colocar os arquivos lá.

**Comment by xR2** [comment]
Sim copiei, drag'n'drop tudo. Nos dois diretórios.

Ah, e aquela field de `urldate` não sei se é padrão. Lembro-me de que quando fiz a gambiarra precisei editar uns fields pois o JabRef estava salvando a data com outro nome e só é preciso apresentá-la quando se tem URL. Não sei como você fez essa parte, mas parece estar funcionando corretamente, pelo menos pra mim hehe.

**Comment by danielbmarques** [comment]
Tente fazer um exemplo mínimo de novo.

Você também pode colar os arquivos `cbx` e `bbx` no próprio diretório do arquivo `tex` que está compilando, ou pode colocá-los em qualquer lugar e usar o endereço inteiro: `style=C:\texlive\2014\texmf-dist\tex\latex\biblatex-abnt\abnt-numeric`.

**Comment by xR2** [comment]
Estou usando o mesmo exemplo de antes, mudei apenas o `style`. Copiar os arquivos para mesma pasta resolve o problema. 
Sera que tenho de entrar no Tex Live Manager e mandar ele atualizar alguma coisa ? É estranho não detectar o arquivo na pasta "certa".

**Comment by danielbmarques** [comment]
```
Copy the .cbx and .bbx files to:

	<TEXMFLOCAL>/tex/latex/biblatex-contrib/<STYLE>/

where <TEXMFLOCAL> denotes the root of the local TeX installation
tree and <STYLE> is the name of the style. Don't forget to update
the file hash tables after installing the files.
```

Você deve ter que atualizar as "file hash tables".
Acho que é só usar o comando `mktexlsr` na linha de comando. Pelo menos aqui no Mac dá certo.

**Comment by xR2** [comment]
Era isso mesmo, agora funcionou.

**Comment by xR2** [comment]
Por algum motivo quando ponho `\printbibliography` da me outro erro... 

> Undefined control sequence.

Mas acho que aí ja deveria abrir outro _issue_, correto?

**Comment by danielbmarques** [comment]
O erro deve estar em outro lugar, vai tentando fazer um MWE até conseguir isolá-lo. Vai acrescentando partes do arquivo que dá erro e compilando até descobrir exatamente onde está o problema. Aí, se tiver algo errado com o estilo, pode abrir outra issue.
