### ISSUE TITLE
Instalação manual em Linux

### ISSUE THREAD

**Issue by fabricix** [abntex/biblatex-abnt#51]
A instalação deve manter a estrutura dos diretórios dentro da pasta mencionada [1]?
Foram copiados os arquivos mencionados (mantendo os diretorios) para a pasta `/usr/share/texlive/texmf-dist/tex/latex/biblatex-contrib/biblatex-abnt` e logo executado o comando `texhash` e tenho o seguinte erro `/usr/share/texlive/texmf-dist/tex/latex/biblatex/biblatex_.sty:11467: Package biblatex Error: Style 'abnt' not found.`

[1] https://github.com/abntex/biblatex-abnt#instala%C3%A7%C3%A3o

**Comment by dbmrq** [comment]
Acho que todo o conteúdo do diretório `latex` pode ser copiado para esse local, sim. Mas tente também copiar os arquivos diretamente; é o mais seguro.

**Comment by fabricix** [comment]
@dbmrq fiz a recomendação e o erro continua `/usr/share/texlive/texmf-dist/tex/latex/biblatex/biblatex_.sty:11467: Package biblatex Error: Style 'abnt' not found. [\RequireBibliographyStyle{\blx@bbxfile}]`

**Comment by fabricix** [comment]
@dbmrq esta issue não esta resolvida? qual a orientação?

**Comment by fabricix** [comment]
@dbmrq tal vez deva-se aclarar que https://github.com/abntex/biblatex-abnt não é testado nem documentado para sistemas linux?

**Comment by dbmrq** [comment]
Esse não é um problema do biblatex-abnt, mas da sua instalação específica, então acho que não faz sentido deixar a issue aberta, já que o pacote está funcionando e está inclusive passando em todos os testes. Não me importo que abram issues assim tangenciais e tento ajudar quando tenho tempo, mas eu deixo abertas as issues que são pendências no desenvolvimento do projeto, e aqui não me parece haver uma pendência. Em termos de orientações, sugiro que você continue tentando identificar o problema. Tente, por exemplo, instalar um outro estilo manualmente e veja se funciona. Se não funcionar, é mais um sinal de que o problema é a instalação, e não o pacote. Ah, e tente reiniciar o computador; às vezes ajuda, rs. Se houver algo que eu possa fazer em relação ao pacote, me avise que eu reabro a issue.

**Comment by fabricix** [comment]
@dbmrq obrigado pela resposta. Nesse caso seria bom aclarar quais as especificações e características do entorno computacional para o qual o pacote está sendo testado e desenvolvido. Ou, pelo menos indicar de forma explicita o entorno requerido (veja por exemplo https://github.com/processing/processing/wiki/Build-Instructions).

**Comment by dbmrq** [comment]
Os testes do Travis atuais são feitos no ubuntu, se não me engano. E eu estou usando o pacote no Linux e no Mac no momento sem problemas. E usei recentemente a instalação manual e via tlmgr, ambas funcionaram. Mas às vezes é meio chato mesmo, e estou disposto a ajudar como conseguir, mesmo por aqui, se você tiver mais informações. Só acho que não faz sentido manter a issue aberta quando não é um problema do pacote. Experimente o que eu falei; tente instalar manualmente qualquer outro estilo e veja se funciona. Assim vamos circunscrevendo o problema.
