### ISSUE TITLE
Estilo abnt-ibid e l3regex

### ISSUE THREAD

**Issue by cereda** [abntex/biblatex-abnt#53]
Amigos,

Considerem o seguinte MWE:

```tex


\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[english]{babel}
\usepackage{csquotes}

\usepackage[style=abnt-ibid]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{doody}
\printbibliography
\end{document}
```

O seguinte erro é reportado:

```
! LaTeX Error: File `l3regex.sty' not found.
```

Vale a nota de que o pacote `l3regex` foi incorporado ao _core_ `expl3` há algum tempo e o _stub_ `.sty` não existe mais. Um patch temporário seria simular o carregamento externo do pacote obsoleto através de `\expandafter\def\csname ver@l3regex.sty\endcsname{}`, mas não entrei em detalhes do estilo para verificar se isso seria suficiente...

Abraços,

Paulo

**Comment by dbmrq** [comment]
Uau, meus ídolos do TeX StackExchange aqui no meu humilde repositório. :open_mouth:

Estou até com vergonha — como vocês devem ter percebido, eu não tenho a menor ideia do que estou fazendo, rs.

Mas muito obrigado pela ajuda! Já aceitei a PR #54, que resolve o problema. :)

**Comment by cereda** [comment]
Fique tranquilo, Daniel! A gente também não sabe o que está fazendo rsrs. :wink: 

Eu gostaria de poder ajudar o projeto, mas no momento não estou conseguindo nem respirar com tanta coisa para fazer. Essas são as agruras do desenvolvimento _opensource_. Mas vale a pena! :wink: 

Grande abraço!
