### ISSUE TITLE
Mesmo autor e ano não adiciona a e b nas referências

### ISSUE THREAD

**Issue by brunotvs** [abntex/biblatex-abnt#59]
Quando duas entradas apresentam o mesmo autor e ano, estas são citadas com o a e b após a data. Isto não ocorre nas referências.

Um exemplo pode ser as entradas de chave romano1996a e romano1996b do seu teste NBR6023-2002_reference

**Comment by laercio-barbosa** [comment]
@brunotvs 

Você tem citações do mesmo autor/ano em dentro do mesmo comando \cite ou \citeonline?

Estou tendo esse mesmo problema que você relatou. Tenho minhas dúvidas se o problema é no **biblatex-abnt** ou se do **abntex2cite**. Anexo segue um MWE. 
[MWE.zip](https://github.com/abntex/biblatex-abnt/files/4548806/MWE.zip)

**Comment by brunotvs** [comment]
Não. Os estudos são citados em locais diferentes.

Não estou utilizando o pacote abntex2cite, apenas o estilo abnt para biblatex.

**Comment by laercio-barbosa** [comment]
Nova informação:

Alterei o estilo logo antes da chamada do arquivo de referências e funciona numa boa.

Fiz:

\bibliographystyle{abntex2-num}
\bibliography{references}

Mantive o "alf" original no usepackage do início

\usepackage[**alf**,bibjustif,abnt-etal-text=it,abnt-repeated-author-omit=yes,abnt-emphasize=bf,abnt-etal-cite=3,abnt-etal-list=0]{abntex2cite}

**Comment by dbmrq** [comment]
https://github.com/abntex/biblatex-abnt/issues/20#issuecomment-287919551

**Comment by dbmrq** [comment]
PS: vocês podem tentar usar a opção `csmdate=both` e/ou dar uma olhada aqui: https://tex.stackexchange.com/q/115866
