### ISSUE TITLE
Undefined control sequence. Com nomes de autores em Patente

### ISSUE THREAD

**Issue by xR2** [abntex/biblatex-abnt#6]
Achei o que estava dando o "novo" erro, parece só afetar as referencias do tipo patente.
A parte (que considero) relevante do log é a seguinte:

> ! Undefined control sequence.
> <argument> ...o {author/editor+others}\clearnames 
>                                                   {author}
> l.35 
>      
> The control sequence at the end of the top line
> of your error message was never \def'ed. If you have
> misspelled it (e.g., `\hobx'), type `I' and the correct
> spelling (e.g., `I\hbox'). Otherwise just continue,
> and I'll forget about whatever was undefined.

Detalhe, quando mudo o `style` para `numeric` por exemplo, não há qualquer erro.
Além disso aparece uma linha repetida com o nome dos autores e tal:
![task2](https://cloud.githubusercontent.com/assets/17341234/16396441/17d6a88c-3c95-11e6-8a61-2510597c5d9f.png)

```
\documentclass[a4paper]{article}
\usepackage[brazil]{babel}
\usepackage{lmodern}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{filecontents}
\usepackage[backend=biber,style=abnt-numeric,language=brazilian]{biblatex}
\usepackage[autostyle]{csquotes}
\addbibresource{shortbib.bib}

\begin{filecontents}{shortbib.bib}
@Patent{garino2015,
  author  = {Terry J. Garino and Tina M. Nenoff and Dorina Florentina Sava Gallis},
  title   = {Densified waste form and method for forming},
  number  = {US9117560B1},
  year    = {2015},
  holder  = {Sandia Corp.},
  note    = {US Patent 9,117,560},
  month   = {Aug},
  url     = {http://www.freepatentsonline.com/9117560.html},
  urldate = {2015-09-07},
}
\end{filecontents}

\begin{document}

    \nocite{*}
    \printbibliography    
\end{document}
```

**Comment by danielbmarques** [comment]
Boa! O erro era meu mesmo.
Já mandei uma atualização pro `develop-2.0`, agora deve estar certo.

A única coisa é que o campo `holder` é um campo de nomes como qualquer outro (e.g. `author` ou `editor`). Então, no seu caso, você tem que usá-lo como um campo de autor corporativo (veja a seção 2.3.3 do manual do biblatex), com um par de chaves a mais: `holder = {{Sandia Corp.}},`.

![captura de tela 2016-06-27 as 19 30 52](https://cloud.githubusercontent.com/assets/15813674/16397950/bebba37a-3c9d-11e6-8fdc-ccd0c21a05b4.png)

**Comment by xR2** [comment]
Não sei se fiz algo errado ou deixei de fazer certo... mas continuo tendo o mesmo erro. Já baixei a versão nova, atualizei os arquivos pelo `mktexlsr`, removi os arquivos auxiliares (não só o bbl) e compilei 3 ou 4 vezes, e continua com mesmo erro.
Tentei rodar com `style=abnt` e também deu mesmo erro.

**Comment by danielbmarques** [comment]
Tem certeza que você atualizou os arquivos em todos os lugares onde tinha posto os velhos?
Pra garantir, tenta colocar os novos na mesma pasta do arquivo `tex`. Se funcionar é porque o problema é na localização dos seus arquivos mesmo.

**Comment by xR2** [comment]
Aha! Na verdade o problema era justamente a existência dessas copias. Agora estou deixando tudo só na pasta original dos pacotes, funcionou.
Mas quando compilo a dissertação continuo um erro, só não consegui isolar qual referencia ainda.

> ! Undefined control sequence.
> <argument> \printname 
>                       {editor}
> \@secondoftwo #1#2->#2
>                       
> \blx@bbx@inproceedings ...tle/organization/editor}
>                                                   \setunit *{\addcomma \adds...
> <argument> ...er \blx@driver \abx@field@entrytype 
>                                                   \blx@postpunct \blx@endlan...

**Comment by danielbmarques** [comment]
Ixi… se quiser me manda seu arquivo de bibliografia todo que eu dou uma olhada.
Como tem alguns tipos de entradas que eu não uso, às vezes acabo quebrando algo sem nem perceber.

**Comment by danielbmarques** [comment]
Ah! Acho que já descobri. Tenta a última versão aqui.

**Comment by xR2** [comment]
Ja estava com o Ctrl C puxado... hehe, achei essa referencia bugado, mas agora está td certo.
E finalmente consigo compilar o trabalho inteiro depois da atualização do texlive.
Em todo caso era essa aqui:
```
@Conference{IAEA_NORM,
  author   = {{IAEA}},
  title    = {Naturally Occurring Radioactive Material (NORM VI)},
  year     = {2010},
  editor   = {{International Atomic Energy Agency}},
  subtitle = {Proceedings of an International Symposium, Marrakech, Morocco, 22 - 26 March 2010},
  series   = {Proceedings Series},
  month    = {March},
  isbn     = {978-92-0-113910-8},
  url      = {http://www-pub.iaea.org/books/IAEABooks/8557/Naturally-Occurring-Radioactive-Material-NORM-VI-Proceedings-of-an-International-Symposium-held-in-Marrakech-Morocco-22-26-March-2010},
  urldate  = {2015-04-24},
  groups   = {IAEA},
}
```

**Comment by danielbmarques** [comment]
Legal! 🎉 
Vou deixar essa issue aberta por mais uns dias também, se tiver mais algum problema avisa.
Valeu pela paciência, é bom ter mais gente ajudando a testar.
