### ISSUE TITLE
Erro ao utilizar \usepackage{hyperref} e \usepackage[brazilian]{babel}

### ISSUE THREAD

**Issue by profiack** [abntex/biblatex-abnt#60]
Amigos,

Se eu utilizo \usepackage{hyperref} e \usepackage[brazilian]{babel} aparentemente não apresenta erros, separa as silabas correto etc, mas a numeração das paginas que aparece ao lado de cada referência na bibliografia ela não leva para o ponto correto do texto e sim para a Capa. Se eu retiro o  \usepackage[brazilian]{babel} , as paginas funcionam normalmente.
Veja abaixo como coloquei em meu codigo
\usepackage[backref=page]{hyperref}
\hypersetup{
  colorlinks   = true, %Colours links instead of ugly boxes
  urlcolor     = blue, %Colour for external hyperlinks
  linkcolor    = blue, %Colour of internal links
  citecolor   = red %Colour of citations
}
\renewcommand*{\backref}[1]{}
\renewcommand*{\backrefalt}[4]{%
    \ifcase #1 (Not cited.)%
    \or        (Citado na pág~#2.)%
   \else      (Citado nas págs~#2.)%
    \fi}

\renewcommand{\bibpreamble}{%
  [Páginas citadas são listadas depois de cada referência.]%
  \par\bigskip}
\renewcommand*{\backrefsep}{, }
\renewcommand*{\backreftwosep}{ e~}
\renewcommand*{\backreflastsep}{, e~}

**Comment by dbmrq** [comment]
Oi, @profiack. Envie um exemplo mínimo que seja compilável, incluindo tudo o que for necessário, mas apenas o que for necessário para reproduzir o problema, por favor. Aí eu dou uma olhada assim que tiver tempo. Obrigado!

**Comment by profiack** [comment]
@dbmrq Obrigado pela resposta, desculpe por não ter respondido antes. Troquei para \usepackage[backref=page]{hyperref} e atualizei todos os pacotes e passou a funcionar. Obrigado
