### ISSUE TITLE
@inproceedings generates unwanted uppercase text

### ISSUE THREAD

**Issue by talespaiva** [abntex/biblatex-abnt#61]
The first word inproceedings'  `booktitle` entry is always in uppercase.

**Example**

This bib item:

```
@inproceedings{anvik2006should,
  title={Who should fix this bug?},
  author={Anvik, John and Hiew, Lyndon and Murphy, Gail C},
  booktitle={Proceedings of the 28th international conference on Software engineering},
  pages={361--370},
  year={2006}
}
```

Generates the following reference:

ANVIK, John; HIEW, Lyndon; MURPHY, Gail C. Who should fix this bug? In:**PROCEEDINGS** of the 28th international conference on Software engineering.[S.l.: s.n.], 2006. p. 361–370.

**Comment by dbmrq** [comment]
Obrigado! Nos últimos tempos não tenho tido tempo de atualizar o estilo, mas vou deixar a issue aqui pra me lembrar de resolver isso ou para, quem sabe, inspirar alguém a fazer uma PR. :)

**Comment by talespaiva** [comment]
Funcionou como eu esperava quando retirei o ```[upperfirst]``` dessa linha: https://github.com/abntex/biblatex-abnt/commit/ca1fc919f2f7b061fda5556d0e956f42930fc7d1#diff-bc4071c26c8a8b24384e158d0d5fb025R590

Como não sei o impacto dessa mudança, prefiro não criar o PR.

Obrigado pela atenção!

**Comment by andregaby** [comment]
Estou com o mesmo problema, como alterar o arquivo ? Não consegui identificar a linha.

**Comment by leonartex** [comment]
Eu não sei bem se isso se configura como um problema. Isso acontece por causa do `booktitle` sem autor do "livro". Esse campo está usando a configuração de quando não existir identificação de autoria ou responsabilidade deixar a primeira palavra em caixa alta. Nesse caso, você pode utilizar o campo `maintitle` no lugar de `booktitle` ou, se existir autor, utilizar também `bookauthor`.

**Comment by dbmrq** [comment]
Maravilha, vou fechar a issue então. Valeu!
