### ISSUE TITLE
biblatex abnt autor data

### ISSUE THREAD

**Issue by Maralvo** [abntex/biblatex-abnt#62]
Estou tendo problemas no meu projeto, a referencia.bib está tudo certo, mas quando rodo no TexStudio não gera o arquivo referências. Já tirei a última vírgula antes da última { e limpei os arquivos auxiliares e nada de funcionar.
Segue abaixo meu arquivo de pacotes. Uso formato biblatex abnt. Quem puder me ajudar a corrigir. 
As citações com vários autores não aparece o et.al

\documentclass[a4paper,12pt,openright,hyphens,twoside,sumario=tradicional,english,brazil]{abntex2}

\makeatletter
\hypersetup{
	pdftitle={\@title}, 
	pdfauthor={\@author},
	pdfsubject={\imprimirpreambulo},
	pdfcreator={Feito no TeXstudio com abnTeX2},
	pdfkeywords={abnt}{latex}{abntex}{abntex2}{trabalho acadêmico}, 
	colorlinks=true,       		% false: boxed links; true: colored links
	allcolors=blue!50!black,
	bookmarksdepth=4
}
\makeatother
\nonfrenchspacing
\usepackage{amsmath,bigints,physics}
\usepackage[fixamsmath]{mathtools}
\usepackage{amssymb}
\raggedbottom
\feetatbottom
\setlength{\skip\footins}{15mm}
%\renewcommand\footnoterule{}

\ifxetex

\usepackage[MnSymbol]{mathspec}
\setmainfont[Numbers={Proportional,Lining},Scale=.9]{Arial}
\setallsansfonts[Scale=MatchLowercase]{Arial}
\renewcommand\familydefault{\sfdefault}
\setallmonofonts[Scale=MatchLowercase]{Consolas}
\setmathsfont(Digits,Latin)[Numbers={Proportional,Lining},Scale=MatchLowercase]{Arial}
\setmathrm[Numbers={Proportional,Lining},Scale=MatchLowercase]{Arial}
\setmathsfont(Greek)[Scale=MatchLowercase]{Arial}
\renewcommand{\partial}{\textit{∂}}
\exchangeforms{epsilon,phi}
\usepackage{polyglossia}
\setdefaultlanguage{brazil}
\setotherlanguage{english}

\else
\usepackage[brazil]{babel}
\selectlanguage{brazil}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
% FONTE CHARTER
\usepackage[scale=0.94,sups,scosf]{XCharter}\usepackage[scale=0.84]{noto-sans}\usepackage[charter,vvarbb,scaled=0.94,varg]{newtxmath}\usepackage{zlmtt}
% FONTE CLASSICO
%\usepackage{jamtimes,newtxtt}\usepackage[sfdefault]{classico}
\usepackage[activate={true,nocompatibility},final,tracking={true,small caps},kerning=true,spacing=true,factor=1000,auto=true,babel]{microtype}
\fi

\usepackage{enumerate}
\usepackage{csquotes}
%\DisemulatePackage{setspace}
%\usepackage{setspace}
\usepackage{titlesec}
\usepackage{siunitx,dcolumn}
\usepackage{graphicx,float,cancel}

\usepackage{multirow,color,xcolor,booktabs,tocloft,pdflscape}

\setlrmarginsandblock{3cm}{2cm}{*}
\setulmarginsandblock{3cm}{2cm}{*}
\checkandfixthelayout

\usepackage[format=plain,font=small,labelfont={bf},labelsep=endash,justification=RaggedRight,position=above]{caption}

\usepackage{nomencl}
\newcommand{\und}[1]{\renewcommand{\nomentryend}{\hspace*{\fill}\si{#1}}}
\newcommand{\widebar}[1]{\mkern 1.5mu\overline{\mkern-1.5mu#1\mkern-1.5mu}\mkern 1.5mu}
\renewcommand{\nomname}{Nomenclatura}
\renewcommand{\nomgroup}[1]{%
	\ifthenelse{\equal{#1}{A}}{\item[\textbf{Alfabeto latino}]}{%
		\ifthenelse{\equal{#1}{G}}{\vskip 2mm\item[\textbf{Alfabeto grego}]}{%
			\ifthenelse{\equal{#1}{C}}{\vskip 2mm\item[\textbf{Abreviaturas}]}{%
				\ifthenelse{\equal{#1}{S}}{\vskip 2mm\item[\textbf{Subscritos, sobrescritos}]}{%
					\ifthenelse{\equal{#1}{Z}}{\vskip 2mm\item[\textbf{Notação matemática}]}
					{}
				}% matches mathematical symbols
			}% matches Subscripts
		}% matches Abbreviations
	}% matches Greek Symbols
}% matches Roman Symbols
%\providecommand{\printnomenclature}{\printglossary}
%\providecommand{\makenomenclature}{\makeglossary}
\makenomenclature
\setlength{\parskip}{0cm}
\setlength\afterchapskip{2cm}
% espaçamento entre linhas 1.5cm segundo ABNT, por padrão a classe antex2 já é 1.5.\OnehalfSpacing (padrão) % or \DoubleSpace para mudar
\setlength{\parindent}{1.3cm}

\renewcommand{\ABNTEXchapterfont}{\bfseries}
\renewcommand{\ABNTEXsectionfont}{\bfseries}
\renewcommand{\ABNTEXsubsectionfont}{\itshape}
\renewcommand{\ABNTEXsubsectionfontsize}{\normalsize}
\renewcommand{\footnotesize}{\small}
\renewcommand{\chaptermark}[1]{\markboth{\chaptername\ \MakeUppercase{\thechapter\  --\  #1}}{}}

\setfloatadjustment{figure}{\centering\small}
\setfloatadjustment{table}{\centering\small}
\setfloatadjustment{algorithm}{\centering\small}
\setlength\textfloatsep{0.5cm}

%\setlength{\textfloatsep}{0pt}
%\setlength{\abovedisplayskip}{12pt}
%\setlength{\belowdisplayskip}{12pt}

\counterwithout*{footnote}{chapter}

\newenvironment{bullets}
{ \begin{list}{\textbullet}{\leftmargin=1.8 \parindent \itemindent=0em \labelsep=1em \itemsep=0em \parsep=0em \topsep=0.25em \parskip=0em \partopsep=0.25em}
	}
	{ \end{list} }

\def\eqdeclaration#1{, veja equação\nobreakspace(#1)}
\def\pagedeclaration#1{, página\nobreakspace#1}
\def\nomname{Nomenclatura}
%\titleformat{\chapter}[display]{\normalfont} {\filcenter \footnotesize CAPÍTULO \thechapter} {2pt} {\LARGE\bfseries\filcenter}

\newenvironment{numerada}
{ \begin{enumerate}[leftmargin=1.8\parindent,parsep=0em,topsep=0.25em,partopsep=0.25em]
	}
	{ \end{enumerate} }
\widowpenalty20000
\clubpenalty20000

% Posiciona figuras e tabelas no topo da página quando adicionadas sozinhas
% em um página em branco. Ver https://github.com/abntex/abntex2/issues/170
\makeatletter
\setlength{\@fptop}{5pt} % Set distance from top of page to first float
\makeatother

\newcommand{\quadroname}{Quadro}
\newcommand{\listofquadrosname}{Lista de quadros}
\newfloat{quadro}{h}{loq}[chapter]
\newlistof{listofquadros}{loq}{\listofquadrosname}
\newlistentry{quadro}{loq}{0}
% configurações para atender às regras da ABNT
\setfloatadjustment{quadro}{\centering}
\counterwithout{quadro}{chapter}
\renewcommand{\cftquadroname}{\quadroname\space} 
\renewcommand*{\cftquadroaftersnum}{\hfill--\hfill}
\setfloatlocations{quadro}{hbtp} 

%\usepackage{geometry}\geometry{left=30mm, top=30mm, right=20mm, bottom=20mm }%considerando sempre frente
%\usepackage[brazilian,hyperpageref]{backref}	 % Paginas com as citações na bibl
%

% --- 
% CONFIGURAÇÕES DE PACOTES
% --- 

% ---
% Configurações do pacote backref
% Usado sem a opção hyperpageref de backref
%\renewcommand{\backrefpagesname}{Citado na(s) página(s):~}
% Texto padrão antes do número das páginas
%\renewcommand{\backref}{}
% Define os textos da citação
%\renewcommand*{\backrefalt}[4]{
  %  \ifcase #1 %
  %  Nenhuma citação no texto.%
  %  \or
  %  Citado na página #2.%
  %  \else
  %  Citado #1 vezes nas páginas #2.%
  %  \fi}%
% ---
%\usepackage[alf,bibjustify]{abntex2cite}
\usepackage[justify,usedashes,backend=biber,noslsn,backref=true,style=abnt]{biblatex}
\DefineBibliographyStrings{brazil}{%
	backrefpage = {Citado na página},% originally "cited on page"
	backrefpages = {Citado nas páginas:},% originally "cited on pages"
}
\addbibresource{capitulos/referencias.bib}
	% Citações padrão ABNT
\renewcommand\UrlFont{\sffamily}
\DeclareFieldFormat{url}{\bibstring{urlfrom}\space\url{#1}}

**Comment by dbmrq** [comment]
Bom dia,

Se você acredita que isso é um bug no biblatex-abnt, envie um exemplo mínimo, por favor. Caso contrário, você pode fazer sua pergunta no [grupo latex-br](https://groups.google.com/forum/#!forum/latex-br), no stack exchange ou em outro lugar mais adequado a questões desse tipo (mas enviar um exemplo mínimo é sempre importante).
