### ISSUE TITLE
Undefined control sequence - Encontrar erro

### ISSUE THREAD

**Issue by arantxax** [abntex/biblatex-abnt#63]
Olá, sou principiante no uso do biblatex-abnt. Me deparei com a mensagem abaixo que não me indica exatamente como posso corrigir o erro. Chequei o arquivo bbl e o arquivo bib... Queria solicitar ajuda para resolvê-lo.
```
`! Undefined control sequence.
\blx@theformat ...m}\addcolon \space \addspaceurl 
                                                  {#1}
l.166 \printbibliography[heading=bay]`
```
-------------------------------------------------------------------------------------
Para reportar seu problema forneça as informações abaixo:
Qual o sistema operacional e versão que está utilizado? Ubuntu 20.04
Qual versão do latex está utilizando? (latex --version) pdfTeX 3.14159265-2.6-1.40.20 (caramba, o número pi!?)
Você está utilizando alguma personalização? Qual? Sim. Configurei o LaTeXStudio para fazer o "Build" usando a opção "Biber".

**Comment by edusantana** [comment]
@arantxax boa noite, seja bem vindo(a)! Eu entendo este problema esteja atrapalhando avançar no seu trabalho. De forma geral, nós dispomos de um pequeno tempo

- [Recomendo seguir estas sugestões](https://github.com/abntex/abntex2/blob/master/CONTRIBUTING.md#antes-de-postar-uma-d%C3%BAvidapergunta)

**Comment by arantxax** [comment]
Obrigada edusantana, pela instrução. Fecharei essa _issue_ porque localizei a fonte do meu problema, o qual não está relacionado com o biblatex.
