### ISSUE TITLE
"et al" deve ser em itálico

### ISSUE THREAD

**Issue by mvlp** [abntex/biblatex-abnt#71]
Prezados,
O et al tanto no texto quanto nas referências aparece em fonte normal e deveria ser em itálico.
De acordo com a 6023:2018, parece que na versão 2002 não tinha esse detalhe.

8.1.1.2 Quando houver quatro ou mais autores, convém indicar todos. Permite-se que se indique
apenas o primeiro, seguido da expressão _et al_.
EXEMPLO 1
URANI, A. _et al_. **Constituição de uma matriz de contabilidade social para o Brasil**. Brasília, DF: IPEA,
1994.

**Comment by mvlp** [comment]
Tem alguma forma de customizar isso temporariamente?
Algum renewcommand ou algo similar?
grato

**Comment by mvlp** [comment]
Consegui uma solução temporária, para aqueles que precisem:

```
\usepackage[style=abnt]{biblatex}

\usepackage{xpatch}

\xpatchbibmacro{name:andothers}{%
  \bibstring{andothers}%
}{%
  \bibstring[\emph]{andothers}%
}{}{}

\addbibresource{referencias.bib}
```

**Comment by douglasrizzo** [comment]
@mvlp se você instalar a branch dev do biblatex-abnt, verá que essa norma e outras da nova NBR 6023:2018 já foram implementadas. Aqui tem uma discussão do que foi implementado: https://github.com/abntex/biblatex-abnt/issues/64#issuecomment-663882991

**Comment by douglasrizzo** [comment]
Eu baixei a branch dev, fiz alguns testes e percebi que o "et al" em itálico não está funcionando mesmo. No trecho abaixo da versão antiga, eu implemento a italicização do "et al" igual a do termo "In". A do "In" funciona, a do "et al", não.

https://github.com/abntex/biblatex-abnt/blob/f97144b49d3d7fcc72d62af53509aed2b180ca7c/latex/bbx/abnt.bbx#L1434-L1440

Eu percebi que o "et al" é chamado através de outras macros, chamadas `name:andothers` e `list:andothers`. Talvez por isso, redefinir a macro `andothers` não funciona. Mas, como eu não sei o que as macros `name:andothers` e `list:andothers` fazem, eu não consigo redefini-las.

Eu mandei a PR #72 com uma implementação alternativa que _define_ a string "et al" em itálico. Isso não é correto e uma alternativa deve ser encontrada, mas acho que cumpre o trabalho por enquanto.

**Comment by douglasrizzo** [comment]
Pronto, usei o comentário do @mvlp para criar uma nova versão da italicização do et al. Está na mesma PR.

**Comment by dbmrq** [comment]
Fiz o merge da PR do @douglasrizzo (obrigado!) e agora isso deve estar resolvido no branch `dev`. 🥳

**Comment by douglasrizzo** [comment]
@mvlp se você verificar essa nova versão da branch dev e tentar gerar seu PDF com ela (e sem o uso da sua solução temporária), dê-nos um feedback.

**Comment by mvlp** [comment]
Funcionou perfeitamente @douglasrizzo , obrigado novamente!
