### ISSUE TITLE
Forma abreviada de mês não segue o idioma original da publicação

### ISSUE THREAD

**Issue by Retroker** [abntex/biblatex-abnt#74]
De acordo com a norma da **ABNT NBR 6023 2018**, no item **8.6.2** (p. 45):

> O mês (se houver) deve anteceder o ano e ser indicado de forma abreviada, no idioma original da
publicação, conforme o Anexo A.

No entanto, de maneira alguma o mês aparece nas referências seguindo as abreviações do **Anexo A**. Todas as referências em inglês, por exemplo, aparecem com mês abreviado em português. Assim, _Março_ aparece como _mar._ ao invés de _Mar._, por exemplo.

Uma sugestão seria fazer a package identificar o campo `langid` (p. 28 de [biblatex](https://mirror.las.iastate.edu/tex-archive/macros/latex/contrib/biblatex/doc/biblatex.pdf)) para fazer o mês seguir a língua correta. No exemplo que citei, bastaria colocar a entrada `langid = {english},` para forçar a mudança.

Obs.: esse problema acontece usando `@Article`, não sei dizer se continua para os outros tipos de entrada.

### Edição:
Uma forma de "forçar" o mês a aparecer da maneira como deveria é trocar o campo `month` pelo campo `issue` (**2.3.10 biblatex**, p.40), por exemplo:
`month = {3},` gera >>> mar.
`issue = {Mar.},` gera >> Mar.

De qualquer maneira, está mais para uma gambiarra e a sugestão continua válida.

**Comment by dbmrq** [comment]
@Retroker Obrigado! Nos últimos tempos não tenho conseguido mexer muito aqui, mas assim que possível vou fazer uma rapa aqui nas issues; vou deixar essa na lista.

**Comment by leonartex** [comment]
@dbmrq, existe algum motivo importante para existir o código `language=brazil` na linha 32 do `\ExecuteBibliographyOptions` no `abnt.bbx`? Pois eu testei aqui e é essa linha que impede o funcionamento do `langid` para usar referências em outros idiomas

**Comment by dbmrq** [comment]
Vixe, se tem um motivo eu não me lembro, rs. Vou aprovar sua PR, valeu!
