### ISSUE TITLE
\cites esta com colchetes no sistema numerico

### ISSUE THREAD

**Issue by xR2** [abntex/biblatex-abnt#8]
Sou eu de novo. Quando uso `\cites` sai colchetes ao invés dos parenteses.

![task2](https://cloud.githubusercontent.com/assets/17341234/16432361/f348ecf2-3d5a-11e6-922c-a49a1bd2cd36.png)

Aproposito, ao usar o numeric eu não posso utilizar os comandos `\textcite` nem `\apud` ? pq?
Na verdade nunca vi um apud pelo sistema numérico.
E mais uma coisinha, o que é aquele `[S.1.]` ?

```
\documentclass[a4paper]{article}
\usepackage[brazil]{babel}
\usepackage{lmodern}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{filecontents}
\usepackage[backend=biber,style=abnt-numeric,language=brazilian]{biblatex}
\usepackage[autostyle]{csquotes}

\addbibresource{shortbib.bib}

\begin{filecontents}{shortbib.bib}

@BOOK{DA,
AUTHOR="John Doe",
TITLE="The Book without Title",
PUBLISHER="Dummy Publisher",
YEAR="2100",
}

@BOOK{DU,
AUTHOR="John Doe",
TITLE="The Book without Title",
PUBLISHER="Dummy Publisher",
YEAR="2100",
}

\end{filecontents}
\begin{document}
    \cites{DA}{DU}
    \printbibliography    
\end{document}
```

**Comment by danielbmarques** [comment]
Resolvido. 😎

Sobre os comandos `\apud` e `\textcite`, eu não uso o sistema numérico, então não sei qual é a regra.
Eu fiz o estilo `abnt-numeric` em 5 minutos no outro dia, então na verdade só dei uma adaptada rápida no numeric original, que não tem comando `apud`; precisaria criar um, como eu fiz no estilo `abnt` normal. Nos próximos dias não vou ter tempo, depois posso dar uma olhada, vou abrir uma outra issue aqui pra marcar isso como por fazer. Já o `textcite` está igual ao original do estilo `numeric`, que não sei como é… mas fica meio esquisito usar o sistema numérico no texto, né? Ficaria, tipo, "Segundo 1, blábláblá"? Não é melhor usar os comandos normais, "Segundo Fulano (1), blábláblá"?

Sobre o "[S.l.]", significa "sine loco", a ABNT manda por isso quando não tem um local de publicação. Como muita gente não gosta, eu coloquei as opções `noslsn`, `nosl` e `nosn`, que servem pra omitir essas abreviações. Dá uma olhada no manual. Elas também podem ser usadas em entradas específicas, é só você colocar um campo `options = {noslsn},`.

**Comment by ycherem** [comment]
Não existe textcite no sistema numérico -- e nunca vi apud.
Em 28 de jun de 2016 6:08 PM, "xR2" <notifications@github.com> escreveu:

**Comment by xR2** [comment]
Sim, atualmente estou usando `\citeauthor{fulano} \cite{fulano}`. O apud realmente é dificil de achar uma explicação decente de como funcionaria no numerico. A abnt é omissa, achei uma tese que utiliza, mas nao da pra confiar.
Se a abnt manda por o SI, assim o faremos. Depois vou passar um pente fino nas minha referencias e adicionar os locations que faltam.
Valeu, sem pressa, só tenho a agradecer.

**Comment by danielbmarques** [comment]
@xR2

Eu arrumei mais alguns detalhes e integrei o branch `develop-2.0` ao `master`.

Você pode atualizar seus arquivos com esses novos e checar se o estilo `abnt-numeric` está funcionando direitinho?

Se estiver tudo certo, já vou enviar a versão 2.0 pro ctan, aí logo mais a atualização já aparece no TeXLive.

**Comment by xR2** [comment]
A princípio esta tudo funcionando como esperando. Aquela duvida sobre _apud_ permanece mas o resultado atual é suficiente. Qualquer coisa eu volto a incomodar hehe.
Muito obrigado.

**Comment by danielbmarques** [comment]
Legal, obrigado pela ajuda!

Quanto ao `apud`, parece não haver uma resposta. A ABNT não fala nada sobre isso e é difícil encontrar alguém que use. E fica meio esquisito, né. Então achei melhor deixar o comando de fora do `biblatex-abnt`. Se alguém realmente quiser, pode criar um só pra si. Posso te ajudar com isso se for o caso.
